-- AgriNexus production foundation schema.
-- Target: PostgreSQL 15+.
-- Notes:
-- - Uses UUIDs generated by the database.
-- - Keeps domain tables explicit so integrations can attach cleanly later.
-- - Avoids provider-specific extensions except pgcrypto for gen_random_uuid().

create extension if not exists pgcrypto;

create table tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table users (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  email text not null,
  display_name text not null,
  password_hash text not null,
  status text not null default 'active',
  preferred_country_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, email)
);

create table roles (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  code text not null,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  unique (tenant_id, code)
);

create table user_roles (
  user_id uuid not null references users(id) on delete cascade,
  role_id uuid not null references roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table countries (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  name text not null,
  iso_code text,
  latitude numeric(10, 6),
  longitude numeric(10, 6),
  zoom integer not null default 6,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, name)
);

alter table users
  add constraint users_preferred_country_fk
  foreign key (preferred_country_id) references countries(id);

create table program_metrics (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  country_id uuid not null references countries(id) on delete cascade,
  patients integer not null default 0,
  facilities integer not null default 0,
  risk_level text not null default 'Low',
  heat_index_c integer,
  queue_status text not null default 'Representative available',
  outcome_rate numeric(5,2) not null default 0,
  adoption_rate numeric(5,2) not null default 0,
  safety_override_rate numeric(5,2) not null default 0,
  data_quality_rate numeric(5,2) not null default 0,
  measured_at timestamptz not null default now()
);

create table facilities (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  country_id uuid not null references countries(id) on delete cascade,
  name text not null,
  facility_type text not null,
  latitude numeric(10, 6),
  longitude numeric(10, 6),
  status text not null default 'active',
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table routes (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  country_id uuid references countries(id),
  name text not null,
  corridor_type text not null default 'trade',
  color text not null default '#176fba',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, name)
);

create table route_checkpoints (
  id uuid primary key default gen_random_uuid(),
  route_id uuid not null references routes(id) on delete cascade,
  sequence integer not null,
  name text not null,
  latitude numeric(10, 6),
  longitude numeric(10, 6),
  checkpoint_type text not null default 'hub',
  metadata jsonb not null default '{}',
  unique (route_id, sequence),
  unique (route_id, name)
);

create table courses (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  code text not null,
  title text not null,
  track text not null,
  readiness_points integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, code)
);

create table learner_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  readiness_score integer not null default 0,
  quiz_score integer not null default 0,
  current_course_id uuid references courses(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table course_enrollments (
  id uuid primary key default gen_random_uuid(),
  learner_profile_id uuid not null references learner_profiles(id) on delete cascade,
  course_id uuid not null references courses(id) on delete cascade,
  status text not null default 'started',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (learner_profile_id, course_id)
);

create table certificates (
  id uuid primary key default gen_random_uuid(),
  learner_profile_id uuid not null references learner_profiles(id) on delete cascade,
  course_id uuid not null references courses(id) on delete cascade,
  certificate_number text not null unique,
  issued_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table workforce_roles (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  title text not null,
  level text not null,
  country_id uuid references countries(id),
  min_readiness integer not null default 0,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table candidate_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  eligibility text not null default 'Locked',
  career_track text not null default 'Foundation Pathway',
  pipeline_stage text not null default 'Profile Review',
  mentor_status text not null default 'Not yet',
  next_shift text not null default 'Awaiting scheduling',
  earnings_estimate numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table job_applications (
  id uuid primary key default gen_random_uuid(),
  candidate_profile_id uuid not null references candidate_profiles(id) on delete cascade,
  workforce_role_id uuid not null references workforce_roles(id) on delete cascade,
  status text not null default 'submitted',
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table patient_intakes (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  country_id uuid not null references countries(id),
  created_by uuid references users(id),
  patient_ref text not null,
  need_summary text not null,
  risk_level text not null default 'Routine',
  queue_status text not null default 'Intake',
  representative_status text not null default 'Not connected',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, patient_ref)
);

create table products (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  country_id uuid references countries(id),
  name text not null,
  category text not null default 'crop',
  unit text not null default 'lot',
  base_price numeric(12,2),
  status text not null default 'active'
);

create table trade_orders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  product_id uuid references products(id),
  country_id uuid not null references countries(id),
  route_id uuid references routes(id),
  active_checkpoint_id uuid references route_checkpoints(id),
  order_number text not null,
  stage text not null default 'Order created',
  buyer_interest integer not null default 0,
  total_amount numeric(12,2) not null default 0,
  created_by uuid references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, order_number)
);

create table wallet_accounts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  currency text not null default 'USD',
  balance numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  wallet_account_id uuid not null references wallet_accounts(id) on delete cascade,
  provider text not null,
  amount numeric(12,2) not null,
  transaction_type text not null default 'credit',
  provider_reference text,
  status text not null default 'posted',
  created_at timestamptz not null default now()
);

create table ai_runs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  user_id uuid references users(id),
  run_type text not null,
  provider text not null,
  model text,
  prompt jsonb not null default '{}',
  response_text text not null,
  response_metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table audit_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references tenants(id) on delete cascade,
  user_id uuid references users(id),
  actor_email text,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index idx_program_metrics_country_measured_at on program_metrics(country_id, measured_at desc);
create index idx_facilities_country on facilities(country_id);
create index idx_route_checkpoints_route on route_checkpoints(route_id, sequence);
create index idx_trade_orders_tenant_stage on trade_orders(tenant_id, stage);
create index idx_patient_intakes_country_status on patient_intakes(country_id, queue_status);
create index idx_ai_runs_tenant_type_created on ai_runs(tenant_id, run_type, created_at desc);
create index idx_audit_events_tenant_created on audit_events(tenant_id, created_at desc);
