"use strict";
const {createId}=require("../contracts/identifiers.js");
function createSyncApi(runtime){return Object.freeze({
  async push(r){permit(r.context,"sync:write");const operations=Array.isArray(r.body.operations)?r.body.operations:[];if(!operations.length)throw bad("At least one sync operation is required.");if(operations.length>100)throw bad("A sync batch cannot exceed 100 operations.");const results=[];for(const operation of operations){await runtime.cutover.requireAuthoritative(operation.workspaceId);results.push(await runtime.sync.apply({...operation,tenantId:r.context.tenantId,userId:r.context.userId,deviceId:req(r.body.deviceId,"Device ID")},applyRecord));}return{status:200,body:{authoritative:true,legacyWriteFallback:false,results}};},
  async pull(r){permit(r.context,"sync:read");return{status:200,body:{authoritative:true,changes:await runtime.sync.changes({tenantId:r.context.tenantId,userId:r.context.userId,deviceId:req(r.query.deviceId,"Device ID"),since:r.query.since||new Date(0),limit:r.query.limit})}};},
  async resolve(r){permit(r.context,"sync:write");return{status:200,body:await runtime.sync.resolve({tenantId:r.context.tenantId,userId:r.context.userId,deviceId:req(r.body.deviceId,"Device ID"),syncId:r.params.syncId,resolution:r.body.resolution,expectedServerVersion:r.body.expectedServerVersion})};}
});}
async function applyRecord({trx,operation,phase,current}){if(operation.entityType!=="record")throw bad(`Unsupported synchronized entity: ${operation.entityType}`);const action=operation.action||"update";if(!["create","update","delete"].includes(action))throw bad(`Unsupported sync action: ${action}`);if(phase==="inspect"){if(!operation.entityId)return null;const result=await trx.query("select record_id,version,data,updated_at from nexus_records where tenant_id=$1 and record_id=$2 and deleted_at is null for update",[operation.tenantId,operation.entityId]);return (result.rows||result)[0]||null;}if(action==="create"){if(current)throw bad("The synchronized record already exists.");const data=operation.payload?.data||{};const recordId=operation.entityId||createId("record");const inserted=await trx.query(`insert into nexus_records(record_id,tenant_id,subject_id,owner_id,task_id,workspace_id,record_type,classification,state,data,provenance)
      values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[recordId,operation.tenantId,operation.payload?.subjectId||null,operation.userId,operation.payload?.taskId||null,operation.workspaceId,req(operation.payload?.recordType,"Record type"),operation.payload?.classification||"standard",operation.payload?.state||"active",data,{...(operation.payload?.provenance||{}),syncDeviceId:operation.deviceId}]);await trx.query("insert into nexus_record_versions(version_id,record_id,version,data,provenance,changed_by) values($1,$2,1,$3,$4,$5)",[createId("recordVersion"),recordId,data,operation.payload?.provenance||{},operation.userId]);return (inserted.rows||inserted)[0];}if(!current)throw bad("The synchronized record does not exist.");if(action==="delete"){const result=await trx.query("update nexus_records set state='deleted',data='{}'::jsonb,deleted_at=now(),version=version+1,updated_at=now() where tenant_id=$1 and record_id=$2 returning *",[operation.tenantId,operation.entityId]);return (result.rows||result)[0];}const data=operation.payload?.data||{};const result=await trx.query("update nexus_records set data=$3,provenance=$4,version=version+1,updated_at=now() where tenant_id=$1 and record_id=$2 returning *",[operation.tenantId,operation.entityId,data,{...(operation.payload?.provenance||{}),syncDeviceId:operation.deviceId}]);const record=(result.rows||result)[0];await trx.query("insert into nexus_record_versions(version_id,record_id,version,data,provenance,changed_by) values($1,$2,$3,$4,$5,$6)",[createId("recordVersion"),operation.entityId,record.version,data,operation.payload?.provenance||{},operation.userId]);return record;}
function permit(context,permission){if(!context.can(permission)&&!context.hasRole("admin"))throw forbidden(permission);}
function req(value,name){if(value===undefined||value===null||value==="")throw bad(`${name} is required.`);return value;}
function bad(message){const error=new Error(message);error.code="invalid_sync_request";error.status=400;return error;}
function forbidden(permission){const error=new Error(`${permission} permission is required.`);error.code="permission_denied";error.status=403;return error;}
module.exports=Object.freeze({createSyncApi});
