"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const workflow = fs.readFileSync(".github/workflows/nexus-release-certification-v2.yml", "utf8");
const registeredWorkflow = fs.readFileSync(".github/workflows/nexus-protected-experience.yml", "utf8");
assert.match(workflow, /workflow_call:/, "registered workflow can reuse managed certification");
assert.match(workflow, /default: false/, "reusable certification must not deploy by default");
assert.match(workflow, /deploy-exact-release:[\s\S]*if: inputs.enforce_release == true/, "deployment is explicitly gated");
assert.match(workflow, /needs:[\s\S]*- foundation[\s\S]*- documents[\s\S]*- release-contract/, "deploy waits for all required gates");
assert.match(workflow, /NEXUS_EXPECTED_RELEASE_SHA: \$\{\{ github.sha \}\}/, "workflow fixes the exact candidate identity");
assert.match(workflow, /group: nexus-managed-cloud-release\s+cancel-in-progress: false/, "do not cancel an in-flight frozen release");
assert.match(workflow, /runs-on: ubuntu-latest/, "managed-cloud runner replaces the former Windows hook bridge");
assert.ok(workflow.includes('secrets.NEXUS_RENDER_DEPLOY_HOOK_URL'), "use managed credential storage");
assert.ok(workflow.includes('test -n "$DEPLOY_HOOK"'), "missing deploy credential fails closed");
assert.ok(workflow.includes('u.searchParams.set("ref",process.env.NEXUS_EXPECTED_RELEASE_SHA)'), "hook requests exact SHA");
assert.match(workflow, /production-certification:[\s\S]*needs: deploy-exact-release/, "certify only after deployment");
assert.match(workflow, /nexus-release-certification-controller.js verify-deployment/, "verify deployed identity");
assert.match(workflow, /nexus-protected-foundation-guard.js/, "retain protected guard");
assert.doesNotMatch(workflow, /GetEnvironmentVariable/, "do not depend on machine-specific Windows credentials");
assert.doesNotMatch(workflow, /console.log\([^\n]*(?:process.env.DEPLOY_HOOK|\bu\.toString)/, "never print deploy credentials");
assert.match(registeredWorkflow, /startsWith\(github.head_ref, 'agent\/certify-nexus-'\)/, "explicit certification PR scope stays protected");
assert.ok(registeredWorkflow.includes('uses: ./.github/workflows/nexus-release-certification-v2.yml'));
console.log("Nexus managed-cloud exact-release deploy bridge contract: PASS");
