
const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const app=fs.readFileSync(require('node:path').join(__dirname,'../../public/app.js'),'utf8');
const start=app.indexOf('async function handleNexusUnifiedBrainRuntimeCommand('),end=app.indexOf('async function handleNexusHealthcareCollaborationRuntimeCommand(',start);
function gateway(handlers={}){const calls=[];const box={...handlers,handleNexusMentalHealthBehavioralWellnessCommand:handlers.mental||(()=>false),handleNexusVisualProviderQuestionReportCommand:handlers.report||(()=>false),handleNexusEnterpriseHealthEvidenceTrustCommand:handlers.evidence||(()=>false),normalizeNexusPresenceRoutableCommand:x=>x,setNexusPresenceState(){},NEXUS_PRESENCE_STATES:{THINKING:'thinking'},nexusActiveWorkflowState:null,nexusAgenticCommandMissions:[],languageCode:()=> 'en',nexusAuthoritativeConversationId:()=> 'conversation',localStorage:{getItem:()=>null},NEXUS_AUTHORITATIVE_TASK_KEY:'task',requestWithTimeout:async(...args)=>{calls.push(args);throw Error('Provider unavailable');},updateNexusBehaviorLayer(){},setVoiceResponse(){}};vm.createContext(box);vm.runInContext(app.slice(start,end),box);return{run:box.handleNexusUnifiedBrainRuntimeCommand,calls};}
test('mental-health local support retains priority over report generation',async()=>{let mental=0;const x=gateway({mental:()=>{mental++;return true;},report:()=>assert.fail('must not displace safety')});assert.equal(await x.run('show doctor questions and crisis help'),true);assert.equal(mental,1);assert.equal(x.calls.length,0);});
test('question preparation remains local and creates no provider request',async()=>{const x=gateway({report:()=>true});assert.equal(await x.run('show questions for my doctor'),true);assert.equal(x.calls.length,0);});
test('explicit source inspection is local while execution intents keep the authoritative gateway',async()=>{let inspected=0;const x=gateway({evidence:()=>{inspected++;return true;}});await x.run('show the source');assert.equal(inspected,1);assert.equal(x.calls.length,0);await x.run('delete health data');assert.equal(inspected,1);assert.equal(x.calls.length,1);assert.equal(x.calls[0][0],'/api/nexus/runtime/behavior/turn');assert.equal(x.calls[0][1].body.text,'delete health data');});

test('Realtime visual-only reports never trigger a second mental-health speech response',()=>{
 const start=app.indexOf('function handleNexusVisualProviderQuestionReportCommand('),end=app.indexOf('function closeNexusVisualProviderQuestionReport(',start);
 const box={window:{NexusMentalHealthBehavioralWellness:{shouldHandle:()=>true}},isNexusVisualProviderQuestionReportCommand:()=>true,handleNexusMentalHealthBehavioralWellnessCommand:()=>assert.fail('no overlapping speech'),openNexusVisualProviderQuestionReport:()=>assert.fail('safety must not be displaced')};
 vm.createContext(box);vm.runInContext(app.slice(start,end),box);
 assert.equal(box.handleNexusVisualProviderQuestionReportCommand('show doctor questions and crisis help',{visualOnly:true,speak:false}),false);
});
