"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {SyncRepository}=require("../../nexus/sync/repository.js");
const {WorkspaceCutoverPolicy}=require("../../nexus/apps/cutover-policy.js");
const {createSyncApi}=require("../../nexus/compat/sync-api.js");
const {registerLegacyTools}=require("../../nexus/compat/legacy-provider-adapter.js");
function db(results=[]){const calls=[];const value={calls,async query(sql,params){calls.push({sql,params});return results.shift()||{rows:[]};},async transaction(work){return work(value);}};return value;}
const context={tenantId:"tenant-1",userId:"user-1",can:p=>["sync:write","sync:read"].includes(p),hasRole:()=>false};
test("offline sync is idempotent and records version conflicts without overwriting server state",async()=>{const store=db([{rows:[]},{rows:[{record_id:"rec-1",version:3}]},{rows:[{sync_id:"syn-1",state:"conflict"}]}]);const repo=new SyncRepository(store);let applied=false;const result=await repo.apply({tenantId:"tenant-1",userId:"user-1",deviceId:"device-1",operationId:"op-1",entityType:"record",entityId:"rec-1",baseVersion:2,payload:{}},async({trx,phase})=>{if(phase==="apply")applied=true;return phase==="inspect"?(await trx.query("record",[])).rows[0]:null;});assert.equal(result.state,"conflict");assert.equal(applied,false);assert.equal(store.calls.some(call=>/insert into nexus_sync_operations/.test(call.sql)),true);});
test("pull and conflict resolution remain tenant user and device scoped",async()=>{const store=db([{rows:[{sync_id:"syn-1"}]},{rows:[{sync_id:"syn-1",state:"pending"}]}]);const repo=new SyncRepository(store);assert.equal((await repo.changes({tenantId:"t",userId:"u",deviceId:"d"})).length,1);await repo.resolve({tenantId:"t",userId:"u",deviceId:"d",syncId:"syn-1",resolution:"retry-client",expectedServerVersion:4});assert.match(store.calls[1].sql,/tenant_id=\$1 and user_id=\$2 and device_id=\$3/);});
test("workspace writes fail closed until authoritative cutover",async()=>{const applications={get:id=>id==="maps"?{applicationId:id}:null};const legacy=new WorkspaceCutoverPolicy({applications,migrations:{status:async()=>({state:"legacy"})}});await assert.rejects(legacy.requireAuthoritative("maps"),error=>error.code==="workspace_not_cut_over"&&error.details.legacyWriteFallback===false);const active=new WorkspaceCutoverPolicy({applications,migrations:{status:async()=>({state:"authoritative"})}});assert.equal((await active.requireAuthoritative("maps")).state,"authoritative");await assert.rejects(active.requireAuthoritative("unknown"),error=>error.code==="workspace_required");});
test("sync push requires cutover and never offers a legacy write fallback",async()=>{const applied=[];const runtime={cutover:{requireAuthoritative:async id=>assert.equal(id,"maps")},sync:{apply:async operation=>{applied.push(operation);return{state:"applied"};}}};const api=createSyncApi(runtime);const result=await api.push({context,body:{deviceId:"device-1",operations:[{workspaceId:"maps",operationId:"op-1",entityType:"record",action:"create",payload:{recordType:"route"}}]}});assert.equal(result.body.legacyWriteFallback,false);assert.equal(applied[0].tenantId,"tenant-1");});
test("authoritative workspace retirement makes compatibility tools unavailable",async()=>{const rows=[];await registerLegacyTools({registry:{register:async row=>(rows.push(row),row)},env:{NEXUS_FILE_UPLOAD_ENABLED:"true"},migrationStatus:async()=>({state:"authoritative"})});assert.equal(rows.every(row=>row.availability==="unavailable"),true);assert.equal(rows.every(row=>row.metadata.migrationState==="retired"),true);assert.equal(rows.every(row=>row.metadata.legacyWriteAllowed===false),true);});
