"use strict";
const assert=require("node:assert/strict");const test=require("node:test");const fs=require("node:fs");const path=require("node:path");
const {RecordRepository}=require("../../nexus/data/record-repository.js");
const {WorkspaceMigrationRepository,REQUIRED_PROOFS}=require("../../nexus/apps/migration-repository.js");
function fakeDb(results=[]){const calls=[];const db={calls,async query(sql,params){calls.push({sql,params});return results.shift()||{rows:[]};},async transaction(work){return work(db);}};return db;}
test("migration supplies versioned tenant records and durable workspace cutover",()=>{const sql=fs.readFileSync(path.join(__dirname,"../../foundation/migrations/007_nexus_workspace_records.sql"),"utf8");for(const table of ["nexus_records","nexus_record_versions","nexus_workspace_migrations"])assert.match(sql,new RegExp(`create table if not exists ${table}`));assert.match(sql,/enable row level security/);});
test("regulated records require a subject and retain immutable versions",async()=>{const db=fakeDb([{rows:[{record_id:"rec_1",version:1}]}]);const repo=new RecordRepository(db);await assert.rejects(repo.create({tenantId:"t",ownerId:"u",workspaceId:"health",recordType:"observation",classification:"health",data:{}}),/subject/);await repo.create({tenantId:"t",ownerId:"u",subjectId:"p",workspaceId:"health",recordType:"observation",classification:"health",data:{bp:"140/90"},provenance:{source:"patient"}});assert.match(db.calls[0].sql,/insert into nexus_records/);assert.match(db.calls[1].sql,/nexus_record_versions/);});
test("record updates enforce optimistic concurrency and tenant scope",async()=>{const db=fakeDb([{rows:[{record_id:"rec_1",version:2}]}]);const repo=new RecordRepository(db);await repo.update({tenantId:"t",recordId:"rec_1",expectedVersion:1,actorId:"u",data:{value:2}});assert.match(db.calls[0].sql,/tenant_id=\$1 and record_id=\$2 and version=\$3/);assert.equal(db.calls[1].params[2],2);});
test("workspace cannot cut over without exact-release proofs and rollback",async()=>{const db=fakeDb([{rows:[{workspace_id:"health",state:"authoritative"}]}]);const repo=new WorkspaceMigrationRepository(db);const releaseSha="a".repeat(40);await assert.rejects(repo.activate({workspaceId:"health",proofs:{contract:true},releaseSha}),/rollback|proof/i);const proofs=Object.fromEntries(REQUIRED_PROOFS.map(k=>[k,{state:"verified",evidenceId:k,releaseSha}]));const result=await repo.activate({workspaceId:"health",proofs,releaseSha,rollbackRef:"refs/tags/nexus-before-health"});assert.equal(result.state,"authoritative");assert.match(db.calls[0].sql,/state='authoritative'/);assert.equal(db.calls[0].params[1].rollback.ref,"refs/tags/nexus-before-health");});
