const assert = require("assert");
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

const testPort = process.env.AGRINEXUS_TEST_PORT || "4373";
const base = process.env.AGRINEXUS_URL || `http://localhost:${testPort}`;
const dbPath = path.join(__dirname, "..", "db.json");
const dbSnapshot = fs.readFileSync(dbPath, "utf8");
let cookie = "";

function wait(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function waitForServer() {
  for (let i = 0; i < 40; i += 1) {
    try {
      await fetch(`${base}/`);
      return;
    } catch {
      await wait(150);
    }
  }
  throw new Error("Server did not become reachable");
}

async function call(path, body) {
  const res = await fetch(`${base}${path}`, {
    method: body ? "POST" : "GET",
    headers: { "content-type": "application/json", cookie },
    body: body ? JSON.stringify(body) : undefined
  });
  const setCookie = res.headers.get("set-cookie");
  if (setCookie) cookie = setCookie.split(";")[0];
  const json = await res.json();
  if (!res.ok) throw new Error(`${path}: ${json.error || res.statusText}`);
  return json;
}

(async () => {
  const server = spawn(process.execPath, ["server.js"], {
    cwd: `${__dirname}/..`,
    env: { ...process.env, PORT: testPort },
    stdio: "ignore",
    windowsHide: true
  });
  await waitForServer();
  const html = await fetch(`${base}/`).then(res => res.text());
  assert(html.includes("Nexus Voice Assistant"));
  assert(html.includes("voiceTextCommand"));
  assert(html.includes("voiceListenBtn"));
  assert(html.includes("guideCommandTourBtn"));
  assert(html.includes("guideTelehealthBtn"));
  assert(html.includes("guideTrainingBtn"));
  assert(html.includes("guideWorkforceBtn"));
  assert(html.includes("guideFarmerMissionBtn"));
  assert(html.includes("guideEnginesBtn"));
  assert(html.includes("pilotRuralAccessBtn"));
  assert(html.includes("pilotFarmerMarketBtn"));
  assert(html.includes("pilotHealthWorkforceBtn"));
  assert(html.includes("simpleHomeTitle"));
  assert(html.includes("personaFarmerBtn"));
  assert(html.includes("personaLearnerBtn"));
  assert(html.includes("personaWorkerBtn"));
  assert(html.includes("personaHealthBtn"));
  assert(html.includes("personaGovernmentBtn"));
  assert(html.includes("personaPartnerBtn"));
  assert(html.includes("jarvisDock"));
  assert(html.includes("jarvisCommandInput"));
  const login = await call("/api/login", { email: "user@agrinexus.org", password: "User2026!" });
  assert(login.user.email === "user@agrinexus.org");
  assert(login.loginProfiles.some(profile => profile.email === "admin@agrinexus.org"));
  assert(login.loginProfiles.some(profile => profile.role === "Investor"));
  assert(login.permissions.learning);
  assert(login.permissions.workforce);
  assert(login.permissions.health);
  assert(login.permissions.trade);
  assert(!login.permissions.admin);
  assert(!login.permissions.integrations);
  const investorLogin = await call("/api/login", { email: "investor@agrinexus.org", password: "Investor2026!" });
  assert(investorLogin.permissions.learning);
  assert(!investorLogin.permissions.admin);
  assert(!investorLogin.permissions.integrations);
  for (const account of [
    { email: "admin@agrinexus.org", password: "Admin2026!" },
    { email: "user@agrinexus.org", password: "User2026!" },
    { email: "investor@agrinexus.org", password: "Investor2026!" }
  ]) {
    const accountLogin = await call("/api/login", account);
    assert(accountLogin.user.email === account.email);
    for (const targetLanguage of ["fr", "sw", "ar", "en"]) {
      const languageState = await call("/api/user/language", { language: targetLanguage });
      assert(languageState.user.email === account.email);
      assert(languageState.user.language === targetLanguage);
      assert(languageState.profile.accessibilityProfile.language === targetLanguage);
    }
  }
  await call("/api/login", { email: "admin@agrinexus.org", password: "Admin2026!" });
  assert(login.providers.length >= 8);
  assert(login.providers.some(provider => provider.id === "voice-stt"));
  assert(login.providers.some(provider => provider.id === "voice-tts"));
  assert(login.providers.some(provider => provider.id === "phone-voice"));
  assert(login.providers.some(provider => provider.id === "translation"));
  assert(login.providers.some(provider => provider.id === "auth-users"));
  assert(login.providers.some(provider => provider.id === "auth-password-reset"));
  assert(login.capabilities.total >= 10);
  assert(login.capabilities.items.some(item => item.id === "jarvis-command-layer"));
  assert(login.capabilities.items.some(item => item.id === "telehealth-workspace"));
  assert(login.smartActions.status);
  assert(Array.isArray(login.smartActions.items));
  assert(login.activationGuide.total >= 6);
  assert(login.activationGuide.groups.some(group => group.id === "ai-voice"));
  assert(login.engineSetup.totalKeys >= 20);
  assert(login.engineSetup.lines.some(item => item.key === "PROVIDER_ENGINE_BASE_URL"));
  assert(login.engineSetup.lines.some(item => item.key === "MAP_TILE_PROVIDER"));
  const nextActions = await call("/api/intelligence/next-actions");
  assert(Array.isArray(nextActions.items));
  assert(nextActions.context.country);
  const renderEnvPlan = await call("/api/engines/render-env-plan");
  assert(renderEnvPlan.groups.some(group => group.id === "telehealth"));
  assert(renderEnvPlan.lines.some(item => item.key === "OPENAI_API_KEY"));
  assert(renderEnvPlan.lines.some(item => item.key === "PROVIDER_ENGINE_BASE_URL"));
  assert(renderEnvPlan.lines.some(item => item.key === "MAP_TILE_PROVIDER"));
  const activationGuide = await call("/api/production/activation-guide");
  assert(activationGuide.groups.some(group => group.id === "telehealth-trade-drone"));
  assert(activationGuide.groups.every(group => Array.isArray(group.env)));
  const completion = await call("/api/production/complete-check");
  assert(completion.total === 10);
  const manifest = await call("/api/engines/manifest");
  assert(manifest.total >= 10);
  assert(manifest.engines.some(engine => engine.id === "live-ai"));
  assert(manifest.engines.some(engine => engine.id === "telehealth"));
  assert(manifest.engines.some(engine => engine.id === "workforce"));
  assert(manifest.engines.some(engine => engine.id === "trade-drone"));
  const liveServiceCheck = await call("/api/production/live-service-check", {});
  assert(liveServiceCheck.liveServiceCheckResult.total >= 7);
  assert(liveServiceCheck.profile.liveServiceChecks.length >= 1);
  assert(liveServiceCheck.profile.integrationEvents.some(event => event.action === "production.live_service_check"));
  const reset = await call("/api/auth/password-reset", { email: "demo@agrinexus.org" });
  assert(reset.ok === true);
  const onboarding = await call("/api/onboarding/start", { scenario: "first-live-pilot" });
  assert(onboarding.profile.onboardingRuns.length >= 1);
  assert(onboarding.profile.integrationEvents.some(event => event.action === "onboarding.started"));
  const support = await call("/api/support/ticket", { subject: "Smoke support ticket", module: "Platform", priority: "standard" });
  assert(support.profile.supportTickets.length >= 1);
  assert(support.profile.integrationEvents.some(event => event.action === "support.ticket_opened"));
  const localPilot = await call("/api/pilot/run", { scenario: "farmer-market" });
  assert(localPilot.pilotResult.status === "pilot-ready");
  assert(localPilot.profile.localPilotRuns.length >= 1);
  assert(localPilot.profile.integrationEvents.some(event => event.action === "pilot.local_run_completed"));
  assert(login.automation.total === 5);
  assert(login.automation.items.some(item => item.id === "live-provider-accounts"));
  assert(login.automation.items.some(item => item.id === "scheduled-background-automation"));
  assert(login.automation.items.some(item => item.id === "event-triggered-workflows"));
  assert(login.automation.items.some(item => item.id === "notification-delivery"));
  assert(login.automation.items.some(item => item.id === "production-user-management"));
  assert(login.admin.modules.length >= 6);
  assert(login.admin.readiness.total >= 12);
  assert(login.admin.readiness.moduleReadiness.length >= 6);
  assert(login.admin.readiness.status === "local-optimized" || login.admin.readiness.status === "production-ready");
  const language = await call("/api/user/language", { language: "fr" });
  assert(language.user.language === "fr");
  assert(language.profile.accessibilityProfile.language === "fr");
  const kenyaContext = await call("/api/context", { countryId: "kenya" });
  assert(kenyaContext.profile.activeCountryId === "kenya");
  assert(kenyaContext.user.language === "sw");
  assert(kenyaContext.profile.accessibilityProfile.language === "sw");
  const egyptContext = await call("/api/context", { countryId: "egypt" });
  assert(egyptContext.profile.activeCountryId === "egypt");
  assert(egyptContext.user.language === "ar");
  assert(egyptContext.profile.accessibilityProfile.language === "ar");
  const drcContext = await call("/api/context", { countryId: "drc" });
  assert(drcContext.profile.activeCountryId === "drc");
  assert(drcContext.user.language === "fr");
  assert(drcContext.profile.accessibilityProfile.language === "fr");
  const nigeriaContext = await call("/api/context", { countryId: "nigeria" });
  assert(nigeriaContext.profile.activeCountryId === "nigeria");
  assert(nigeriaContext.user.language === "en");
  assert(nigeriaContext.profile.accessibilityProfile.language === "en");
  const englishLanguage = await call("/api/user/language", { language: "en" });
  assert(englishLanguage.user.language === "en");
  assert(englishLanguage.profile.accessibilityProfile.language === "en");
  const catalog = await call("/api/learning/catalog");
  assert(catalog.catalog.total >= 6);
  assert(catalog.catalog.courses.some(course => course.id === "telehealth-support"));
  assert(catalog.catalog.courses.every(course => course.accessibility.length >= 3));
  const started = await call("/api/learning/start", { courseId: "digital-foundations" });
  assert(started.profile.readiness >= 36);
  assert(started.profile.enrollments.length >= 1);
  assert(started.profile.enrollments[0].progress >= 25);
  assert(started.profile.integrationEvents.some(event => event.action === "course.started"));
  const lesson = await call("/api/learning/lesson", { courseId: "digital-foundations", moduleIndex: 0 });
  const lessonEnrollment = lesson.profile.enrollments.find(item => item.courseId === "digital-foundations");
  assert(lessonEnrollment.completedModules.includes(0));
  assert(lessonEnrollment.progress >= 45);
  assert(lesson.profile.integrationEvents.some(event => event.action === "lesson.completed"));
  const lessonIntelligence = await call("/api/intelligence/workflow", { module: "Learning workflow", action: "Complete lesson" });
  assert(lessonIntelligence.profile.workflowIntelligence.length >= 1);
  assert(lessonIntelligence.workflowIntelligenceResult.nextStep.includes("lesson") || lessonIntelligence.workflowIntelligenceResult.nextStep.includes("certificate"));
  assert(lessonIntelligence.profile.integrationEvents.some(event => event.action === "workflow.intelligence_generated"));
  const quiz = await call("/api/learning/quiz", {});
  assert(quiz.profile.quizScore >= 25);
  assert(quiz.profile.integrationEvents.some(event => event.action === "quiz.completed"));
  const cert = await call("/api/learning/certificate", {});
  assert(cert.profile.certificates.length >= 1);
  const certifiedCourse = cert.profile.certificates[cert.profile.certificates.length - 1]?.courseId || cert.profile.activeCourseId;
  assert(cert.profile.completedCourses.includes(certifiedCourse));
  assert(cert.profile.integrationEvents.some(event => event.action === "certificate.issued"));
  const learningAccess = await call("/api/learning/accessibility", { courseId: "digital-foundations", mode: "caption" });
  assert(learningAccess.profile.learningAccommodations.length >= 1);
  assert(learningAccess.profile.integrationEvents.some(event => event.action === "learning.accessibility_ready"));
  const assignment = await call("/api/learning/advanced", { type: "assignment", courseId: "digital-foundations" });
  assert(assignment.profile.learningAssignments.length >= 1);
  assert(assignment.profile.integrationEvents.some(event => event.action === "learning.assignment_created"));
  const quizAttempt = await call("/api/learning/advanced", { type: "quiz-attempt", courseId: "digital-foundations" });
  assert(quizAttempt.profile.quizAttempts.length >= 1);
  const instructorNote = await call("/api/learning/advanced", { type: "note", courseId: "digital-foundations" });
  assert(instructorNote.profile.instructorNotes.length >= 1);
  const progressReport = await call("/api/learning/advanced", { type: "report", courseId: "digital-foundations" });
  assert(progressReport.profile.learningProgressReports.length >= 1);
  const transcript = await call("/api/learning/advanced", { type: "transcript", courseId: "digital-foundations" });
  assert(transcript.profile.learningTranscripts.length >= 1);
  const cohort = await call("/api/learning/advanced", { type: "cohort", courseId: "digital-foundations" });
  assert(cohort.profile.learningCohorts.length >= 1);
  const built = await call("/api/workforce/action", { type: "build-profile" });
  assert(built.profile.workforceBadges.includes("Profile Verified"));
  assert(built.profile.integrationEvents.some(event => event.action === "profile.verified"));
  const applied = await call("/api/workforce/apply", { roleId: "field-agent" });
  assert(applied.profile.applications.length >= 1);
  assert(applied.profile.integrationEvents.some(event => event.action === "application.submitted"));
  const interview = await call("/api/workforce/action", { type: "interview" });
  assert(interview.profile.interviews >= 1);
  assert(interview.profile.integrationEvents.some(event => event.action === "interview.scheduled"));
  assert(interview.profile.integrationEvents.some(event => event.action === "notification.sent"));
  const mentor = await call("/api/workforce/action", { type: "mentor" });
  assert(mentor.profile.mentor === "Assigned");
  assert(mentor.profile.integrationEvents.some(event => event.action === "mentor.assigned"));
  const shift = await call("/api/workforce/action", { type: "shift" });
  assert(shift.profile.shiftSchedule.length >= 1);
  assert(shift.profile.integrationEvents.some(event => event.action === "shift.scheduled"));
  const workforceOnboarding = await call("/api/workforce/advanced", { type: "onboarding" });
  assert(workforceOnboarding.profile.workforceOnboarding.length >= 1);
  assert(workforceOnboarding.profile.integrationEvents.some(event => event.action === "onboarding.packet_ready"));
  const documents = await call("/api/workforce/advanced", { type: "document" });
  assert(documents.profile.workforceDocuments.length >= 1);
  const timesheet = await call("/api/workforce/advanced", { type: "timesheet", hours: 6 });
  assert(timesheet.profile.timesheets.length >= 1);
  const payroll = await call("/api/workforce/advanced", { type: "payroll" });
  assert(payroll.profile.payrollApprovals.length >= 1);
  const evaluation = await call("/api/workforce/advanced", { type: "evaluation" });
  assert(evaluation.profile.performanceReviews.length >= 1);
  const shiftRequest = await call("/api/workforce/advanced", { type: "shift-request" });
  assert(shiftRequest.profile.shiftRequests.length >= 1);
  const intake = await call("/api/health/action", {
    type: "intake",
    patientName: "Amina Okafor",
    needSummary: "Hearing-impaired patient needs heat exposure review and low-bandwidth follow-up",
    urgency: "Priority",
    preferredLanguage: "en",
    accessibilityNeeds: "Captions, audio narration, caregiver handoff",
    contactMethod: "Low-bandwidth callback",
    caregiverName: "Community accessibility aide"
  });
  assert(intake.profile.healthIntakes.length >= 1);
  assert(intake.profile.healthIntakes[0].patientName === "Amina Okafor");
  assert(intake.profile.healthIntakes[0].accessibilityNeeds.includes("Captions"));
  assert(intake.profile.healthIntakes[0].contactMethod === "Low-bandwidth callback");
  assert(intake.profile.integrationEvents.some(event => event.action === "intake.created"));
  const guidedIntake = await call("/api/health/intake-simulation", {
    patientName: "Fatima Hassan",
    needSummary: "Arabic-speaking rural patient needs accessible telehealth intake simulation",
    preferredLanguage: "ar",
    accessibilityNeeds: "Arabic captions, audio narration, caregiver handoff",
    contactMethod: "Voice callback plus SMS summary"
  });
  assert(guidedIntake.intakeSimulationResult.intake.patientName === "Fatima Hassan");
  assert(guidedIntake.profile.telehealthConsents.length >= 1);
  assert(guidedIntake.profile.telehealthVitals.length >= 1);
  assert(guidedIntake.profile.telehealthAccessibility.length >= 1);
  assert(guidedIntake.profile.telehealthReferrals.length >= 1);
  assert(guidedIntake.profile.telehealthFollowUps.length >= 1);
  assert(guidedIntake.profile.integrationEvents.some(event => event.action === "telehealth.followup_scheduled"));
  const representative = await call("/api/health/action", { type: "representative" });
  assert(representative.profile.representativeConnections >= 1);
  assert(representative.profile.integrationEvents.some(event => event.action === "representative.connected"));
  const safety = await call("/api/health/action", { type: "safety" });
  assert(safety.profile.safetyReviews.length >= 1);
  assert(safety.profile.integrationEvents.some(event => event.action === "safety.review"));
  const inspector = await call("/api/health/action", { type: "inspector" });
  assert(inspector.profile.aiRuns.some(run => run.type === "inspector"));
  assert(inspector.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Healthcare"));
  const carePlan = await call("/api/health/action", { type: "careplan" });
  assert(carePlan.profile.carePlans.length >= 1);
  assert(carePlan.profile.integrationEvents.some(event => event.action === "care_plan.synced"));
  assert(carePlan.profile.aiRuns.some(run => run.type === "careplan"));
  assert(carePlan.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Healthcare"));
  const accessPlan = await call("/api/health/action", { type: "accessibility" });
  assert(accessPlan.profile.telehealthAccessibility.length >= 1);
  assert(accessPlan.profile.integrationEvents.some(event => event.action === "telehealth.accessibility_plan"));
  const captionRelay = await call("/api/health/action", { type: "caption" });
  assert(captionRelay.profile.integrationEvents.some(event => event.action === "telehealth.caption_relay"));
  const caregiverNotice = await call("/api/health/action", { type: "caregiver" });
  assert(caregiverNotice.profile.integrationEvents.some(event => event.action === "telehealth.caregiver_notified"));
  const consent = await call("/api/health/action", { type: "consent" });
  assert(consent.profile.telehealthConsents.length >= 1);
  assert(consent.profile.integrationEvents.some(event => event.action === "telehealth.consent_recorded"));
  const vitals = await call("/api/health/action", { type: "vitals" });
  assert(vitals.profile.telehealthVitals.length >= 1);
  assert(vitals.profile.integrationEvents.some(event => event.action === "telehealth.vitals_captured"));
  const referral = await call("/api/health/action", { type: "referral" });
  assert(referral.profile.telehealthReferrals.length >= 1);
  assert(referral.profile.integrationEvents.some(event => event.action === "telehealth.referral_sent"));
  const followUp = await call("/api/health/action", { type: "followup" });
  assert(followUp.profile.telehealthFollowUps.length >= 1);
  assert(followUp.profile.integrationEvents.some(event => event.action === "telehealth.followup_scheduled"));
  const appointment = await call("/api/health/advanced", { type: "appointment" });
  assert(appointment.profile.telehealthAppointments.length >= 1);
  assert(appointment.profile.integrationEvents.some(event => event.action === "telehealth.appointment_scheduled"));
  const providerAssignment = await call("/api/health/advanced", { type: "provider" });
  assert(providerAssignment.profile.telehealthProviderAssignments.length >= 1);
  const patientHistory = await call("/api/health/advanced", { type: "history" });
  assert(patientHistory.profile.patientHistoryRecords.length >= 1);
  const prescriptionPacket = await call("/api/health/advanced", { type: "prescription" });
  assert(prescriptionPacket.profile.telehealthPrescriptionPackets.length >= 1);
  const emergency = await call("/api/health/advanced", { type: "emergency" });
  assert(emergency.profile.telehealthEmergencyEscalations.length >= 1);
  const careNote = await call("/api/health/advanced", { type: "note", note: "Care team confirmed accessible callback and caregiver handoff." });
  assert(careNote.profile.careTeamNotes.length >= 1);
  const outcome = await call("/api/health/advanced", { type: "outcome" });
  assert(outcome.profile.telehealthOutcomeReviews.length >= 1);
  assert(outcome.profile.integrationEvents.some(event => event.action === "telehealth.outcome_reviewed"));
  const providerTest = await call("/api/integrations/test", { providerId: "openai" });
  assert(providerTest.profile.integrationEvents.some(event => event.action === "provider.test"));
  const learningModuleTest = await call("/api/integrations/test-module", { module: "Learning" });
  assert(learningModuleTest.profile.integrationEvents.some(event => event.action === "provider.test_module" && event.module === "Learning"));
  const workforceModuleTest = await call("/api/integrations/test-module", { module: "Workforce" });
  assert(workforceModuleTest.profile.integrationEvents.some(event => event.action === "provider.test_module" && event.module === "Workforce"));
  const healthModuleTest = await call("/api/integrations/test-module", { module: "Healthcare" });
  assert(healthModuleTest.profile.integrationEvents.some(event => event.action === "provider.test_module" && event.module === "Healthcare"));
  const providerTestAll = await call("/api/integrations/test-all", {});
  assert(providerTestAll.profile.integrationEvents.some(event => event.action === "provider.test_all"));
  const admin = await call("/api/admin/health-check", {});
  assert(admin.admin.audit.length >= 1);
  assert(admin.profile.integrationEvents.some(event => event.action === "admin.health_check"));
  const billing = await call("/api/billing/checkout", { plan: "standard" });
  assert(billing.billingResult.status);
  assert(billing.profile.integrationEvents.some(event => event.action === "billing.checkout_requested"));
  const subscriber = await call("/api/admin/subscriber", { name: "Pilot subscriber", email: "pilot-user@example.com", plan: "pilot", seats: 1 });
  assert(subscriber.admin.subscribers.length >= 1);
  assert(subscriber.profile.integrationEvents.some(event => event.action === "subscriber.invited"));
  const order = await call("/api/trade/order", { productId: "avocado-ke" });
  assert(order.profile.orders.length >= 1);
  assert(order.profile.tradeEvents.some(event => event.type === "order.created"));
  const advanced = await call("/api/trade/advance", {});
  assert(advanced.profile.orders[advanced.profile.orders.length - 1].timeline.length >= 3);
  const wallet = await call("/api/trade/wallet", { provider: "M-Pesa", amount: 120 });
  assert(wallet.profile.walletTransactions.length >= 1);
  assert(wallet.profile.integrationEvents.some(event => event.action === "wallet.transaction"));
  const droneMission = await call("/api/trade/drone-mission", { productId: "avocado-ke" });
  assert(droneMission.profile.droneMissions.length >= 1);
  assert(droneMission.profile.integrationEvents.some(event => event.action === "drone.flight_plan"));
  assert(droneMission.profile.mapInsights.some(item => item.type === "drone-flight-plan"));
  const drone = await call("/api/trade/drone-scan", { productId: "avocado-ke" });
  assert(drone.profile.droneScans.length >= 1);
  assert(drone.profile.droneFindings.length >= 1);
  assert(drone.profile.droneScans[0].cropHealthScore >= 55);
  assert(drone.profile.integrationEvents.some(event => event.action === "drone.field_scan"));
  assert(drone.profile.mapInsights.some(item => item.type === "drone-field-scan"));
  const droneIntervention = await call("/api/trade/drone-intervention", {});
  assert(droneIntervention.profile.fieldInterventions.length >= 1);
  assert(droneIntervention.profile.integrationEvents.some(event => event.action === "drone.intervention_task"));
  assert(droneIntervention.profile.mapInsights.some(item => item.type === "drone-intervention"));
  const droneReport = await call("/api/trade/drone-advanced", { type: "field-report", productId: "avocado-ke" });
  assert(droneReport.profile.droneFieldReports.length >= 1);
  assert(droneReport.profile.integrationEvents.some(event => event.action === "drone.field_report"));
  const irrigationPlan = await call("/api/trade/drone-advanced", { type: "irrigation", productId: "avocado-ke" });
  assert(irrigationPlan.profile.droneIrrigationPlans.length >= 1);
  const pestAlert = await call("/api/trade/drone-advanced", { type: "pest", productId: "avocado-ke" });
  assert(pestAlert.profile.dronePestAlerts.length >= 1);
  const sprayPlan = await call("/api/trade/drone-advanced", { type: "spray", productId: "avocado-ke" });
  assert(sprayPlan.profile.droneSprayPlans.length >= 1);
  const yieldForecast = await call("/api/trade/drone-advanced", { type: "yield", productId: "avocado-ke" });
  assert(yieldForecast.profile.droneYieldForecasts.length >= 1);
  const droneCompliance = await call("/api/trade/drone-advanced", { type: "compliance", productId: "avocado-ke" });
  assert(droneCompliance.profile.droneComplianceAudits.length >= 1);
  assert(droneCompliance.profile.mapInsights.some(item => item.type === "drone.compliance_audit"));
  const ai = await call("/api/ai/run", { type: "command" });
  assert(ai.profile.aiActivity.length > 20);
  assert(ai.profile.aiRuns.length >= 1);
  assert(ai.profile.aiRuns[0].type === "command");
  assert(ai.profile.mapInsights.length >= 1);
  assert(ai.profile.integrationEvents.some(event => event.action === "ai.run"));
  const farmerLocation = await call("/api/map/advanced", { type: "farmer-location" });
  assert(farmerLocation.profile.farmerLocations.length >= 1);
  assert(farmerLocation.profile.integrationEvents.some(event => event.action === "map.farmer_location_mapped"));
  const fieldZone = await call("/api/map/advanced", { type: "field-zone" });
  assert(fieldZone.profile.fieldZones.length >= 1);
  assert(fieldZone.profile.integrationEvents.some(event => event.action === "map.field_zone_created"));
  const facilityRoute = await call("/api/map/advanced", { type: "facility-route" });
  assert(facilityRoute.profile.facilityRoutes.length >= 1);
  assert(facilityRoute.profile.integrationEvents.some(event => event.action === "map.facility_route_ready"));
  const routeDisruption = await call("/api/map/advanced", { type: "disruption" });
  assert(routeDisruption.profile.routeDisruptions.length >= 1);
  assert(routeDisruption.profile.integrationEvents.some(event => event.action === "map.route_disruption_recorded"));
  const riskLayer = await call("/api/map/advanced", { type: "risk-layer" });
  assert(riskLayer.profile.mapRiskLayers.length >= 1);
  assert(riskLayer.profile.integrationEvents.some(event => event.action === "map.risk_layer_generated"));
  const mapEvidence = await call("/api/map/advanced", { type: "evidence" });
  assert(mapEvidence.profile.mapEvidencePackets.length >= 1);
  assert(mapEvidence.profile.mapInsights.some(item => item.type === "map.evidence_packet_ready"));
  const tutorAi = await call("/api/ai/run", { type: "tutor" });
  assert(tutorAi.profile.aiRuns[0].type === "tutor");
  assert(tutorAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Learning"));
  const workforceAi = await call("/api/ai/run", { type: "workforce-coach" });
  assert(workforceAi.profile.aiRuns[0].type === "workforce-coach");
  assert(workforceAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Workforce"));
  const triageAi = await call("/api/ai/run", { type: "triage" });
  assert(triageAi.profile.aiRuns[0].type === "triage");
  assert(triageAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Healthcare"));
  const tradeAi = await call("/api/ai/run", { type: "trade-advisor" });
  assert(tradeAi.profile.aiRuns[0].type === "trade-advisor");
  assert(tradeAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "AgriTrade"));
  const copilotAi = await call("/api/ai/run", { type: "copilot" });
  assert(copilotAi.profile.aiRuns[0].type === "copilot");
  assert(copilotAi.profile.aiRuns[0].reviewStatus === "pending-human-review");
  const reviewedAi = await call("/api/ai/review", { runId: copilotAi.profile.aiRuns[0].id, decision: "approve", note: "Smoke review" });
  assert(reviewedAi.profile.aiRuns[0].reviewStatus === "approved");
  assert(reviewedAi.profile.integrationEvents.some(event => event.action === "ai.reviewed"));
  const agentPlan = await call("/api/agent/plan", { goal: "Move a rural learner through training, workforce, telehealth, trade, maps, and AI evidence." });
  assert(agentPlan.profile.agentPlans.length >= 1);
  assert(agentPlan.profile.agentPlans[0].steps.length >= 7);
  assert(agentPlan.profile.integrationEvents.some(event => event.action === "agent.plan_created"));
  const briefing = await call("/api/agent/briefing", { purpose: "government presentation" });
  assert(briefing.profile.agentBriefings.length >= 1);
  assert(briefing.profile.integrationEvents.some(event => event.action === "agent.briefing_created"));
  const agentExecution = await call("/api/agent/execute", { planId: agentPlan.profile.agentPlans[0].id });
  assert(agentExecution.profile.agentExecutions.length >= 1);
  assert(agentExecution.profile.agentPlans[0].status === "executed");
  assert(agentExecution.profile.agentExecutions[0].status === "completed");
  assert(agentExecution.profile.agentExecutions[0].steps.every(step => step.status === "executed"));
  assert(agentExecution.profile.agentMemory.lastStatus === "completed");
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.ai.copilot"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.learning.start_or_continue"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.workforce.match_role"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.drone.flight_plan"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.drone.field_scan"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.drone.intervention_task"));
  const voiceStatus = await call("/api/agent/command", { command: "what is the readiness status", confirm: true });
  assert(voiceStatus.commandResult.intent === "readiness-summary");
  assert(voiceStatus.profile.agentCommands.length >= 1);
  assert(voiceStatus.profile.integrationEvents.some(event => event.action === "agent.command"));
  const voiceTranscript = await call("/api/voice/transcribe", { transcript: "run telehealth intake", language: "en" });
  assert(voiceTranscript.voiceResult.transcript === "run telehealth intake");
  assert(voiceTranscript.profile.voiceSessions.some(item => item.type === "speech-to-text"));
  const voiceSpeak = await call("/api/voice/speak", { text: "Telehealth command ready", language: "en" });
  assert(voiceSpeak.voiceResult.text === "Telehealth command ready");
  assert(voiceSpeak.profile.voiceSessions.some(item => item.type === "text-to-speech"));
  const phoneIncoming = await fetch(`${base}/api/voice/phone/incoming`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ From: "+15555550123", CallSid: "CA-smoke" })
  });
  const phoneIncomingXml = await phoneIncoming.text();
  assert(phoneIncoming.ok);
  assert(phoneIncomingXml.includes("<Gather"));
  const phoneGather = await fetch(`${base}/api/voice/phone/gather`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ SpeechResult: "start telehealth intake", CallSid: "CA-smoke" })
  });
  const phoneGatherXml = await phoneGather.text();
  assert(phoneGather.ok);
  assert(phoneGatherXml.includes("You can say another command"));
  const translated = await call("/api/translate", { text: "Generate care plan", targetLanguage: "sw", context: "smoke" });
  assert(translated.translationResult.targetLanguage === "sw");
  assert(translated.profile.integrationEvents.some(event => event.action === "translation.dynamic"));
  const voiceTranslated = await call("/api/translate", { text: "Telehealth intake opened for voice user", targetLanguage: "sw", context: "voice-response" });
  assert(voiceTranslated.translationResult.translatedText.includes("afya"));
  const voiceDrone = await call("/api/agent/command", { command: "run drone scan", confirm: true });
  assert(voiceDrone.commandResult.intent === "drone.field_scan");
  assert(voiceDrone.profile.droneScans.length >= 1);
  assert(voiceDrone.profile.agentCommands[0].intent === "drone.field_scan");
  const buyerContact = await call("/api/agent/command", { command: "Hey AgriTrade, I want to speak to the buyer that I am selling my crop to", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(buyerContact.commandResult.intent === "trade.buyer_contact");
  assert(buyerContact.commandResult.metadata.redirectSection === "trade");
  assert(buyerContact.profile.buyerContacts.length >= 1);
  assert(buyerContact.profile.integrationEvents.some(event => event.action === "buyer.contact_prepared"));
  const quote = await call("/api/trade/advanced", { type: "quote", productId: "avocado-ke" });
  assert(quote.profile.tradeQuotes.length >= 1);
  assert(quote.profile.integrationEvents.some(event => event.action === "quote.sent"));
  const quality = await call("/api/trade/advanced", { type: "quality", productId: "avocado-ke" });
  assert(quality.profile.qualityInspections.length >= 1);
  const coldChain = await call("/api/trade/advanced", { type: "cold-chain", productId: "avocado-ke" });
  assert(coldChain.profile.coldChainChecks.length >= 1);
  const exportPacket = await call("/api/trade/advanced", { type: "export", productId: "avocado-ke" });
  assert(exportPacket.profile.exportReadiness.length >= 1);
  const contract = await call("/api/trade/advanced", { type: "contract", productId: "avocado-ke" });
  assert(contract.profile.contractPackets.length >= 1);
  const release = await call("/api/trade/advanced", { type: "release", productId: "avocado-ke" });
  assert(release.profile.paymentReleases.length >= 1);
  const workforceApply = await call("/api/agent/command", { command: "Workforce, I want to apply for that job can you help me", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(["workforce.application_submitted", "workforce.application_help"].includes(workforceApply.commandResult.intent));
  assert(workforceApply.commandResult.metadata.redirectSection === "workforce");
  const conversationalApply = await call("/api/agent/command", { command: "I want to apply for that job", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(conversationalApply.commandResult.intent === "conversation.pending_action");
  assert(conversationalApply.commandResult.status === "needs-confirmation");
  assert(conversationalApply.profile.agentPendingAction.kind === "workforce-application");
  assert(conversationalApply.profile.agentConversation.length >= 2);
  const conversationalConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(conversationalConfirm.commandResult.intent === "conversation.confirmed");
  assert(!conversationalConfirm.profile.agentPendingAction);
  assert(conversationalConfirm.commandResult.metadata.redirectSection === "workforce");
  const guidedHealth = await call("/api/agent/command", { command: "health", conversational: true });
  assert(guidedHealth.commandResult.intent === "conversation.pending_action");
  assert(guidedHealth.commandResult.metadata.redirectSection === "health");
  const cancelGuidedHealth = await call("/api/agent/command", { command: "no", conversational: true });
  assert(cancelGuidedHealth.commandResult.intent === "conversation.canceled");
  const agenticOpenCommand = await call("/api/agent/command", { command: "My field has crop stress and I need evidence before selling", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agenticOpenCommand.commandResult.intent === "conversation.pending_action");
  assert(["drone.field_scan", "trade.market_review", "drone.intervention_task"].includes(agenticOpenCommand.commandResult.metadata.tool));
  assert(agenticOpenCommand.profile.agentPendingAction.tool);
  const agenticConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agenticConfirm.commandResult.intent === "conversation.confirmed");
  assert(!agenticConfirm.profile.agentPendingAction);
  const rememberPreference = await call("/api/agent/command", { command: "Remember that I prefer voice-first telehealth support for hearing impaired patients", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(rememberPreference.commandResult.intent === "memory-updated");
  assert(rememberPreference.profile.agentMemory.preferences.length >= 1);
  const memoryRouted = await call("/api/agent/command", { command: "A patient cannot hear and needs care access", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(memoryRouted.commandResult.intent === "conversation.pending_action");
  assert(memoryRouted.commandResult.metadata.memoriesUsed.length >= 1);
  assert(memoryRouted.profile.integrationEvents.some(event => event.action === "agent.memory_retrieved"));
  const memorySummary = await call("/api/agent/command", { command: "what have you learned", conversational: true });
  assert(memorySummary.commandResult.intent === "memory-summary");
  assert(memorySummary.commandResult.response.includes("voice-first telehealth"));
  const autopilotPreview = await call("/api/agent/command", { command: "Nexus autopilot help this farmer get from crop problem to buyer payment", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(autopilotPreview.commandResult.intent === "conversation.pending_action");
  assert(autopilotPreview.commandResult.metadata.mode === "autopilot");
  assert(autopilotPreview.commandResult.metadata.previewSteps.length >= 6);
  const autopilotConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(autopilotConfirm.commandResult.intent === "conversation.confirmed");
  assert(autopilotConfirm.commandResult.metadata.mode === "autopilot");
  assert(autopilotConfirm.profile.agentExecutions[0].status === "completed");
  assert(autopilotConfirm.profile.integrationEvents.some(event => event.action === "agent.autopilot_executed"));
  const lessonCommand = await call("/api/agent/command", { command: "Nexus complete my lesson", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(lessonCommand.commandResult.intent === "learning.complete_lesson");
  assert(lessonCommand.commandResult.metadata.redirectSection === "learning");
  const certificateCommand = await call("/api/agent/command", { command: "Nexus issue my certificate", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(certificateCommand.commandResult.intent === "learning.certificate");
  assert(certificateCommand.profile.certificates.length >= 1);
  const vitalsCommand = await call("/api/agent/command", { command: "Nexus capture vitals for telehealth", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(vitalsCommand.commandResult.intent === "health.vitals");
  assert(vitalsCommand.commandResult.metadata.redirectSection === "health");
  const shiftCommand = await call("/api/agent/command", { command: "Nexus schedule my shift", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(shiftCommand.commandResult.intent === "workforce.schedule_shift");
  assert(shiftCommand.profile.shiftSchedule.length >= 1);
  const engineCommand = await call("/api/agent/command", { command: "Nexus test provider engines", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(engineCommand.commandResult.intent === "integrations.test_all");
  assert(engineCommand.commandResult.metadata.redirectSection === "integrations");
  const govtBriefing = await call("/api/agent/command", { command: "Nexus, prepare a government briefing", confirm: true });
  assert(govtBriefing.commandResult.intent === "government-briefing");
  assert(govtBriefing.profile.agentBriefings.length >= 1);
  const farmerPlan = await call("/api/agent/command", { command: "Nexus, onboard a farmer in Kenya", confirm: false });
  assert(farmerPlan.commandResult.intent === "create-agent-plan");
  assert(farmerPlan.profile.agentMemory.lastStatus === "awaiting-approval");
  const jarvisMission = await call("/api/agent/command", { command: "Nexus, run full mission", confirm: true });
  assert(jarvisMission.commandResult.intent === "full-agent-mission");
  assert(jarvisMission.profile.agentExecutions[0].status === "completed");
  const notice = await call("/api/notifications/send", { module: "Learning", channel: "workflow", message: "Learning notification smoke" });
  assert(notice.profile.notifications.some(item => item.module === "Learning"));
  assert(notice.profile.integrationEvents.some(event => event.action === "notification.sent" && event.module === "Learning"));
  const demo = await call("/api/demo/run", {});
  assert(demo.profile.activity.some(item => item.includes("Executive demo run completed")));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.learning_completed"));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.workforce_synced"));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.health_case_opened"));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.trade_order_created"));
  assert(demo.profile.notifications.some(item => item.channel === "executive-demo"));
  const wowDemo = await call("/api/demo/wow", {});
  assert(wowDemo.profile.demoScore === 100);
  assert(wowDemo.profile.demoMoments.length >= 6);
  assert(wowDemo.profile.learningAccommodations.length >= 3);
  assert(wowDemo.profile.telehealthAccessibility.length >= 3);
  assert(wowDemo.profile.integrationEvents.some(event => event.action === "wow.telehealth_accessible"));
  assert(wowDemo.profile.integrationEvents.some(event => event.action === "wow.ai_orchestration"));
  assert(wowDemo.profile.notifications.some(item => item.channel === "wow-demo"));
  server.kill();
  fs.writeFileSync(dbPath, dbSnapshot);
  console.log("Smoke test passed");
})().catch(error => {
  fs.writeFileSync(dbPath, dbSnapshot);
  console.error(error.message);
  process.exit(1);
});
