const assert = require("assert");
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

const testPort = process.env.AGRINEXUS_TEST_PORT || String(4373 + Math.floor(Math.random() * 400));
const base = process.env.AGRINEXUS_URL || `http://localhost:${testPort}`;
const dbPath = path.join(__dirname, "..", "db.json");
const dbSnapshot = fs.readFileSync(dbPath, "utf8");
const tempDbPath = path.join(__dirname, "..", `tmp-smoke-db-${process.pid}-${testPort}.json`);
let cookie = "";
let serverProcess = null;

function resetConversationMemory(db) {
  db.profile = db.profile || {};
  db.profile.agentPendingAction = null;
  db.profile.activeCourseId = "digital-foundations";
  db.profile.completedCourses = (db.profile.completedCourses || []).filter(courseId => courseId !== "digital-foundations");
  db.profile.certificates = (db.profile.certificates || []).filter(item => item.courseId !== "digital-foundations");
  db.profile.enrollments = (db.profile.enrollments || []).filter(item => item.courseId !== "digital-foundations");
  db.profile.agentMemory = {
    ...(db.profile.agentMemory || {}),
    activeClarification: null,
    activeGuidedMission: null,
    activeIntake: null,
    activeJarvisSession: null,
    activeRecovery: null,
    activeVoiceMission: null,
    lastRecommendedAction: null,
    turnCoach: null,
    userModel: {}
  };
  return db;
}

function wait(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function waitForServer() {
  for (let i = 0; i < 40; i += 1) {
    try {
      await fetch(`${base}/`);
      return;
    } catch {
      await wait(150);
    }
  }
  throw new Error("Server did not become reachable");
}

async function call(path, body) {
  const res = await fetch(`${base}${path}`, {
    method: body ? "POST" : "GET",
    headers: { "content-type": "application/json", cookie },
    body: body ? JSON.stringify(body) : undefined
  });
  const setCookie = res.headers.get("set-cookie");
  if (setCookie) cookie = setCookie.split(";")[0];
  const json = await res.json();
  if (!res.ok) throw new Error(`${path}: ${json.error || res.statusText}`);
  return json;
}

(async () => {
  const isolatedDb = resetConversationMemory(JSON.parse(dbSnapshot));
  fs.writeFileSync(tempDbPath, JSON.stringify(isolatedDb, null, 2));
  const server = spawn(process.execPath, ["server.js"], {
    cwd: `${__dirname}/..`,
    env: { ...process.env, PORT: testPort, AGRINEXUS_DB_PATH: tempDbPath },
    stdio: "ignore",
    windowsHide: true
  });
  serverProcess = server;
  await waitForServer();
  const html = await fetch(`${base}/`).then(res => res.text());
  assert(html.includes("Nexus Voice Assistant"));
  assert(html.includes("voiceTextCommand"));
  assert(html.includes("voiceListenBtn"));
  assert(html.includes("guideConversationBtn"));
  assert(html.includes("Conversation-first guide"));
  assert(html.includes("pilotRuralAccessBtn"));
  assert(html.includes("pilotFarmerMarketBtn"));
  assert(html.includes("pilotHealthWorkforceBtn"));
  assert(html.includes("simpleHomeTitle"));
  assert(html.includes("personaFarmerBtn"));
  assert(html.includes("personaLearnerBtn"));
  assert(html.includes("personaWorkerBtn"));
  assert(html.includes("personaHealthBtn"));
  assert(html.includes("personaGovernmentBtn"));
  assert(html.includes("personaPartnerBtn"));
  assert(html.includes("jarvisDock"));
  assert(html.includes("jarvisCommandInput"));
  const login = await call("/api/login", { email: "user@agrinexus.org", password: "User2026!" });
  assert(login.user.email === "user@agrinexus.org");
  assert(login.loginProfiles.some(profile => profile.email === "admin@agrinexus.org"));
  assert(login.loginProfiles.some(profile => profile.role === "Investor"));
  assert(login.permissions.learning);
  assert(login.permissions.workforce);
  assert(login.permissions.health);
  assert(login.permissions.trade);
  assert(!login.permissions.admin);
  assert(!login.permissions.integrations);
  const investorLogin = await call("/api/login", { email: "investor@agrinexus.org", password: "Investor2026!" });
  assert(investorLogin.permissions.learning);
  assert(!investorLogin.permissions.admin);
  assert(!investorLogin.permissions.integrations);
  for (const account of [
    { email: "admin@agrinexus.org", password: "Admin2026!" },
    { email: "user@agrinexus.org", password: "User2026!" },
    { email: "investor@agrinexus.org", password: "Investor2026!" }
  ]) {
    const accountLogin = await call("/api/login", account);
    assert(accountLogin.user.email === account.email);
    for (const targetLanguage of ["fr", "sw", "ar", "en"]) {
      const languageState = await call("/api/user/language", { language: targetLanguage });
      assert(languageState.user.email === account.email);
      assert(languageState.user.language === targetLanguage);
      assert(languageState.profile.accessibilityProfile.language === targetLanguage);
    }
  }
  await call("/api/login", { email: "admin@agrinexus.org", password: "Admin2026!" });
  assert(login.providers.length >= 8);
  assert(login.providers.some(provider => provider.id === "voice-stt"));
  assert(login.providers.some(provider => provider.id === "voice-tts"));
  assert(login.providers.some(provider => provider.id === "phone-voice"));
  assert(login.providers.some(provider => provider.id === "translation"));
  assert(login.providers.some(provider => provider.id === "auth-users"));
  assert(login.providers.some(provider => provider.id === "auth-password-reset"));
  assert(login.capabilities.total >= 10);
  assert(login.intelligentAssistant.total === 10);
  assert(login.intelligentAssistant.items.some(item => item.id === "goal-driven-operating-brain"));
  assert(login.intelligentAssistant.items.some(item => item.id === "persistent-memory"));
  assert(login.intelligentAssistant.items.some(item => item.id === "live-context-awareness"));
  assert(login.intelligentAssistant.items.some(item => item.id === "evidence-and-mobile-initiative"));
  assert(login.sessionBriefing.title);
  assert(login.sessionBriefing.prompts.includes("summarize my progress"));
  assert(login.sessionBriefing.assistantReadiness.total === 10);
  assert(login.behaviorModel.id === "human-guide-behavior-model");
  assert(login.behaviorModel.turnPattern.length >= 5);
  assert(login.behaviorModel.principles.some(item => item.includes("short natural")));
  assert(login.behaviorModel.audience.includes("low-tech"));
  assert(login.behaviorModel.interactionStyle.includes("voice-first"));
  assert(login.behaviorModel.lowTechBehaviors.some(item => item.includes("one clear question")));
  assert(login.capabilities.items.some(item => item.id === "agrinexus-command-layer"));
  assert(login.capabilities.items.some(item => item.id === "telehealth-workspace"));
  assert(login.smartActions.status);
  assert(Array.isArray(login.smartActions.items));
  assert(login.activationGuide.total >= 6);
  assert(login.activationGuide.groups.some(group => group.id === "ai-voice"));
  assert(login.engineSetup.totalKeys >= 20);
  assert(login.engineSetup.lines.some(item => item.key === "PROVIDER_ENGINE_BASE_URL"));
  assert(login.engineSetup.lines.some(item => item.key === "MAP_TILE_PROVIDER"));
  const nextActions = await call("/api/intelligence/next-actions");
  assert(Array.isArray(nextActions.items));
  assert(nextActions.context.country);
  const renderEnvPlan = await call("/api/engines/render-env-plan");
  assert(renderEnvPlan.groups.some(group => group.id === "telehealth"));
  assert(renderEnvPlan.lines.some(item => item.key === "OPENAI_API_KEY"));
  assert(renderEnvPlan.lines.some(item => item.key === "PROVIDER_ENGINE_BASE_URL"));
  assert(renderEnvPlan.lines.some(item => item.key === "MAP_TILE_PROVIDER"));
  const activationGuide = await call("/api/production/activation-guide");
  assert(activationGuide.groups.some(group => group.id === "telehealth-trade-drone"));
  assert(activationGuide.groups.every(group => Array.isArray(group.env)));
  const completion = await call("/api/production/complete-check");
  assert(completion.total === 10);
  const manifest = await call("/api/engines/manifest");
  assert(manifest.total >= 10);
  assert(manifest.engines.some(engine => engine.id === "live-ai"));
  assert(manifest.engines.some(engine => engine.id === "telehealth"));
  assert(manifest.engines.some(engine => engine.id === "workforce"));
  assert(manifest.engines.some(engine => engine.id === "trade-drone"));
  const liveServiceCheck = await call("/api/production/live-service-check", {});
  assert(liveServiceCheck.liveServiceCheckResult.total >= 7);
  assert(liveServiceCheck.profile.liveServiceChecks.length >= 1);
  assert(liveServiceCheck.profile.integrationEvents.some(event => event.action === "production.live_service_check"));
  const reset = await call("/api/auth/password-reset", { email: "demo@agrinexus.org" });
  assert(reset.ok === true);
  const onboarding = await call("/api/onboarding/start", { scenario: "first-live-pilot" });
  assert(onboarding.profile.onboardingRuns.length >= 1);
  assert(onboarding.profile.integrationEvents.some(event => event.action === "onboarding.started"));
  const support = await call("/api/support/ticket", { subject: "Smoke support ticket", module: "Platform", priority: "standard" });
  assert(support.profile.supportTickets.length >= 1);
  assert(support.profile.integrationEvents.some(event => event.action === "support.ticket_opened"));
  const localPilot = await call("/api/pilot/run", { scenario: "farmer-market" });
  assert(localPilot.pilotResult.status === "pilot-ready");
  assert(localPilot.profile.localPilotRuns.length >= 1);
  assert(localPilot.profile.integrationEvents.some(event => event.action === "pilot.local_run_completed"));
  const telehealthPartner = await call("/api/partnership/create", { type: "telehealth", note: "Provider partnership smoke" });
  assert(telehealthPartner.partnershipResult.title.includes("Telehealth"));
  assert(telehealthPartner.profile.providerPartnerships.length >= 1);
  assert(telehealthPartner.profile.providerPartnerships[0].requiredCredentials.includes("HEALTH_TELEHEALTH_WEBHOOK_URL"));
  assert(telehealthPartner.profile.integrationEvents.some(event => event.action === "provider.partnership_packet_created"));
  const providerCandidates = await call("/api/providers/candidates");
  assert(providerCandidates.total >= 20);
  assert(providerCandidates.groups.some(group => group.id === "course-catalog"));
  assert(providerCandidates.groups.some(group => group.id === "job-network"));
  assert(providerCandidates.groups.some(group => group.id === "telehealth-provider"));
  assert(providerCandidates.groups.some(group => group.id === "ehr-fhir"));
  assert(providerCandidates.groups.some(group => group.id === "buyer-marketplace"));
  assert(providerCandidates.groups.some(group => group.id === "drone-data"));
  assert(providerCandidates.groups.some(group => group.id === "logistics-payment"));
  const shortlistedProvider = await call("/api/providers/candidates/shortlist", { candidateId: "eosda" });
  assert(shortlistedProvider.providerCandidateShortlistResult.candidateId === "eosda");
  assert(shortlistedProvider.profile.providerShortlist.some(item => item.candidateId === "eosda"));
  assert(shortlistedProvider.profile.integrationEvents.some(event => event.action === "provider.candidate_shortlisted"));
  const logisticsPartner = await call("/api/partnership/create", { type: "logistics", note: "Logistics provider smoke" });
  assert(logisticsPartner.partnershipResult.title.includes("Logistics"));
  assert(logisticsPartner.partnershipResult.candidateProviders.length >= 1);
  const dronePartnerCommand = await call("/api/agent/command", { command: "Nexus, create a drone provider partnership packet", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(dronePartnerCommand.commandResult.intent === "provider.partnership_packet_created");
  assert(dronePartnerCommand.commandResult.metadata.type === "drone");
  assert(dronePartnerCommand.profile.providerPartnerships[0].type === "drone");
  assert(login.automation.total === 5);
  assert(login.automation.items.some(item => item.id === "live-provider-accounts"));
  assert(login.automation.items.some(item => item.id === "scheduled-background-automation"));
  assert(login.automation.items.some(item => item.id === "event-triggered-workflows"));
  assert(login.automation.items.some(item => item.id === "notification-delivery"));
  assert(login.automation.items.some(item => item.id === "production-user-management"));
  assert(login.admin.modules.length >= 6);
  assert(login.admin.readiness.total >= 12);
  assert(login.admin.readiness.moduleReadiness.length >= 6);
  assert(login.admin.readiness.status === "local-optimized" || login.admin.readiness.status === "production-ready");
  const language = await call("/api/user/language", { language: "fr" });
  assert(language.user.language === "fr");
  assert(language.profile.accessibilityProfile.language === "fr");
  const kenyaContext = await call("/api/context", { countryId: "kenya" });
  assert(kenyaContext.profile.activeCountryId === "kenya");
  assert(kenyaContext.user.language === "sw");
  assert(kenyaContext.profile.accessibilityProfile.language === "sw");
  const egyptContext = await call("/api/context", { countryId: "egypt" });
  assert(egyptContext.profile.activeCountryId === "egypt");
  assert(egyptContext.user.language === "ar");
  assert(egyptContext.profile.accessibilityProfile.language === "ar");
  const drcContext = await call("/api/context", { countryId: "drc" });
  assert(drcContext.profile.activeCountryId === "drc");
  assert(drcContext.user.language === "fr");
  assert(drcContext.profile.accessibilityProfile.language === "fr");
  const nigeriaContext = await call("/api/context", { countryId: "nigeria" });
  assert(nigeriaContext.profile.activeCountryId === "nigeria");
  assert(nigeriaContext.user.language === "en");
  assert(nigeriaContext.profile.accessibilityProfile.language === "en");
  const englishLanguage = await call("/api/user/language", { language: "en" });
  assert(englishLanguage.user.language === "en");
  assert(englishLanguage.profile.accessibilityProfile.language === "en");
  const catalog = await call("/api/learning/catalog");
  assert(catalog.catalog.total >= 6);
  assert(catalog.catalog.courses.some(course => course.id === "telehealth-support"));
  assert(catalog.catalog.courses.every(course => course.accessibility.length >= 3));
  const started = await call("/api/learning/start", { courseId: "digital-foundations" });
  assert(started.profile.readiness >= 36);
  assert(started.profile.enrollments.length >= 1);
  assert(started.profile.enrollments[0].progress >= 25);
  assert(started.profile.integrationEvents.some(event => event.action === "course.started"));
  const lesson = await call("/api/learning/lesson", { courseId: "digital-foundations", moduleIndex: 0 });
  const lessonEnrollment = lesson.profile.enrollments.find(item => item.courseId === "digital-foundations");
  assert(lessonEnrollment.completedModules.includes(0));
  assert(lessonEnrollment.progress >= 45);
  assert(lesson.profile.integrationEvents.some(event => event.action === "lesson.completed"));
  const lessonIntelligence = await call("/api/intelligence/workflow", { module: "Learning workflow", action: "Complete lesson" });
  assert(lessonIntelligence.profile.workflowIntelligence.length >= 1);
  assert(lessonIntelligence.workflowIntelligenceResult.nextStep.includes("lesson") || lessonIntelligence.workflowIntelligenceResult.nextStep.includes("certificate"));
  assert(lessonIntelligence.profile.integrationEvents.some(event => event.action === "workflow.intelligence_generated"));
  const quiz = await call("/api/learning/quiz", {});
  assert(quiz.profile.quizScore >= 25);
  assert(quiz.profile.integrationEvents.some(event => event.action === "quiz.completed"));
  const cert = await call("/api/learning/certificate", {});
  assert(cert.profile.certificates.length >= 1);
  const certifiedCourse = cert.profile.certificates[cert.profile.certificates.length - 1]?.courseId || cert.profile.activeCourseId;
  assert(cert.profile.completedCourses.includes(certifiedCourse));
  assert(cert.profile.integrationEvents.some(event => event.action === "certificate.issued"));
  const learningAccess = await call("/api/learning/accessibility", { courseId: "digital-foundations", mode: "caption" });
  assert(learningAccess.profile.learningAccommodations.length >= 1);
  assert(learningAccess.profile.integrationEvents.some(event => event.action === "learning.accessibility_ready"));
  const assignment = await call("/api/learning/advanced", { type: "assignment", courseId: "digital-foundations" });
  assert(assignment.profile.learningAssignments.length >= 1);
  assert(assignment.profile.integrationEvents.some(event => event.action === "learning.assignment_created"));
  const quizAttempt = await call("/api/learning/advanced", { type: "quiz-attempt", courseId: "digital-foundations" });
  assert(quizAttempt.profile.quizAttempts.length >= 1);
  const instructorNote = await call("/api/learning/advanced", { type: "note", courseId: "digital-foundations" });
  assert(instructorNote.profile.instructorNotes.length >= 1);
  const progressReport = await call("/api/learning/advanced", { type: "report", courseId: "digital-foundations" });
  assert(progressReport.profile.learningProgressReports.length >= 1);
  const transcript = await call("/api/learning/advanced", { type: "transcript", courseId: "digital-foundations" });
  assert(transcript.profile.learningTranscripts.length >= 1);
  const cohort = await call("/api/learning/advanced", { type: "cohort", courseId: "digital-foundations" });
  assert(cohort.profile.learningCohorts.length >= 1);
  const built = await call("/api/workforce/action", { type: "build-profile" });
  assert(built.profile.workforceBadges.includes("Profile Verified"));
  assert(built.profile.integrationEvents.some(event => event.action === "profile.verified"));
  const applied = await call("/api/workforce/apply", { roleId: "field-agent" });
  assert(applied.profile.applications.length >= 1);
  assert(applied.profile.integrationEvents.some(event => event.action === "application.submitted"));
  const interview = await call("/api/workforce/action", { type: "interview" });
  assert(interview.profile.interviews >= 1);
  assert(interview.profile.integrationEvents.some(event => event.action === "interview.scheduled"));
  assert(interview.profile.integrationEvents.some(event => event.action === "notification.sent"));
  const mentor = await call("/api/workforce/action", { type: "mentor" });
  assert(mentor.profile.mentor === "Assigned");
  assert(mentor.profile.integrationEvents.some(event => event.action === "mentor.assigned"));
  const shift = await call("/api/workforce/action", { type: "shift" });
  assert(shift.profile.shiftSchedule.length >= 1);
  assert(shift.profile.integrationEvents.some(event => event.action === "shift.scheduled"));
  const workforceOnboarding = await call("/api/workforce/advanced", { type: "onboarding" });
  assert(workforceOnboarding.profile.workforceOnboarding.length >= 1);
  assert(workforceOnboarding.profile.integrationEvents.some(event => event.action === "onboarding.packet_ready"));
  const documents = await call("/api/workforce/advanced", { type: "document" });
  assert(documents.profile.workforceDocuments.length >= 1);
  const timesheet = await call("/api/workforce/advanced", { type: "timesheet", hours: 6 });
  assert(timesheet.profile.timesheets.length >= 1);
  const payroll = await call("/api/workforce/advanced", { type: "payroll" });
  assert(payroll.profile.payrollApprovals.length >= 1);
  const evaluation = await call("/api/workforce/advanced", { type: "evaluation" });
  assert(evaluation.profile.performanceReviews.length >= 1);
  const shiftRequest = await call("/api/workforce/advanced", { type: "shift-request" });
  assert(shiftRequest.profile.shiftRequests.length >= 1);
  const intake = await call("/api/health/action", {
    type: "intake",
    patientName: "Amina Okafor",
    needSummary: "Hearing-impaired patient needs heat exposure review and low-bandwidth follow-up",
    urgency: "Priority",
    preferredLanguage: "en",
    accessibilityNeeds: "Captions, audio narration, caregiver handoff",
    contactMethod: "Low-bandwidth callback",
    caregiverName: "Community accessibility aide"
  });
  assert(intake.profile.healthIntakes.length >= 1);
  assert(intake.profile.healthIntakes[0].patientName === "Amina Okafor");
  assert(intake.profile.healthIntakes[0].accessibilityNeeds.includes("Captions"));
  assert(intake.profile.healthIntakes[0].contactMethod === "Low-bandwidth callback");
  assert(intake.profile.integrationEvents.some(event => event.action === "intake.created"));
  const guidedIntake = await call("/api/health/intake-simulation", {
    patientName: "Fatima Hassan",
    needSummary: "Arabic-speaking rural patient needs accessible telehealth intake simulation",
    preferredLanguage: "ar",
    accessibilityNeeds: "Arabic captions, audio narration, caregiver handoff",
    contactMethod: "Voice callback plus SMS summary"
  });
  assert(guidedIntake.intakeSimulationResult.intake.patientName === "Fatima Hassan");
  assert(guidedIntake.profile.telehealthConsents.length >= 1);
  assert(guidedIntake.profile.telehealthVitals.length >= 1);
  assert(guidedIntake.profile.telehealthAccessibility.length >= 1);
  assert(guidedIntake.profile.telehealthReferrals.length >= 1);
  assert(guidedIntake.profile.telehealthFollowUps.length >= 1);
  assert(guidedIntake.profile.integrationEvents.some(event => event.action === "telehealth.followup_scheduled"));
  const representative = await call("/api/health/action", { type: "representative" });
  assert(representative.profile.representativeConnections >= 1);
  assert(representative.profile.integrationEvents.some(event => event.action === "representative.connected"));
  const safety = await call("/api/health/action", { type: "safety" });
  assert(safety.profile.safetyReviews.length >= 1);
  assert(safety.profile.integrationEvents.some(event => event.action === "safety.review"));
  const inspector = await call("/api/health/action", { type: "inspector" });
  assert(inspector.profile.aiRuns.some(run => run.type === "inspector"));
  assert(inspector.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Healthcare"));
  const carePlan = await call("/api/health/action", { type: "careplan" });
  assert(carePlan.profile.carePlans.length >= 1);
  assert(carePlan.profile.integrationEvents.some(event => event.action === "care_plan.synced"));
  assert(carePlan.profile.aiRuns.some(run => run.type === "careplan"));
  assert(carePlan.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Healthcare"));
  const accessPlan = await call("/api/health/action", { type: "accessibility" });
  assert(accessPlan.profile.telehealthAccessibility.length >= 1);
  assert(accessPlan.profile.integrationEvents.some(event => event.action === "telehealth.accessibility_plan"));
  const captionRelay = await call("/api/health/action", { type: "caption" });
  assert(captionRelay.profile.integrationEvents.some(event => event.action === "telehealth.caption_relay"));
  const caregiverNotice = await call("/api/health/action", { type: "caregiver" });
  assert(caregiverNotice.profile.integrationEvents.some(event => event.action === "telehealth.caregiver_notified"));
  const consent = await call("/api/health/action", { type: "consent" });
  assert(consent.profile.telehealthConsents.length >= 1);
  assert(consent.profile.integrationEvents.some(event => event.action === "telehealth.consent_recorded"));
  const vitals = await call("/api/health/action", { type: "vitals" });
  assert(vitals.profile.telehealthVitals.length >= 1);
  assert(vitals.profile.integrationEvents.some(event => event.action === "telehealth.vitals_captured"));
  const referral = await call("/api/health/action", { type: "referral" });
  assert(referral.profile.telehealthReferrals.length >= 1);
  assert(referral.profile.integrationEvents.some(event => event.action === "telehealth.referral_sent"));
  const followUp = await call("/api/health/action", { type: "followup" });
  assert(followUp.profile.telehealthFollowUps.length >= 1);
  assert(followUp.profile.integrationEvents.some(event => event.action === "telehealth.followup_scheduled"));
  const appointment = await call("/api/health/advanced", { type: "appointment" });
  assert(appointment.profile.telehealthAppointments.length >= 1);
  assert(appointment.profile.integrationEvents.some(event => event.action === "telehealth.appointment_scheduled"));
  const providerAssignment = await call("/api/health/advanced", { type: "provider" });
  assert(providerAssignment.profile.telehealthProviderAssignments.length >= 1);
  const patientHistory = await call("/api/health/advanced", { type: "history" });
  assert(patientHistory.profile.patientHistoryRecords.length >= 1);
  const prescriptionPacket = await call("/api/health/advanced", { type: "prescription" });
  assert(prescriptionPacket.profile.telehealthPrescriptionPackets.length >= 1);
  const emergency = await call("/api/health/advanced", { type: "emergency" });
  assert(emergency.profile.telehealthEmergencyEscalations.length >= 1);
  const careNote = await call("/api/health/advanced", { type: "note", note: "Care team confirmed accessible callback and caregiver handoff." });
  assert(careNote.profile.careTeamNotes.length >= 1);
  const outcome = await call("/api/health/advanced", { type: "outcome" });
  assert(outcome.profile.telehealthOutcomeReviews.length >= 1);
  assert(outcome.profile.integrationEvents.some(event => event.action === "telehealth.outcome_reviewed"));
  const providerTest = await call("/api/integrations/test", { providerId: "openai" });
  assert(providerTest.profile.integrationEvents.some(event => event.action === "provider.test"));
  const learningModuleTest = await call("/api/integrations/test-module", { module: "Learning" });
  assert(learningModuleTest.profile.integrationEvents.some(event => event.action === "provider.test_module" && event.module === "Learning"));
  const workforceModuleTest = await call("/api/integrations/test-module", { module: "Workforce" });
  assert(workforceModuleTest.profile.integrationEvents.some(event => event.action === "provider.test_module" && event.module === "Workforce"));
  const healthModuleTest = await call("/api/integrations/test-module", { module: "Healthcare" });
  assert(healthModuleTest.profile.integrationEvents.some(event => event.action === "provider.test_module" && event.module === "Healthcare"));
  const providerTestAll = await call("/api/integrations/test-all", {});
  assert(providerTestAll.profile.integrationEvents.some(event => event.action === "provider.test_all"));
  const admin = await call("/api/admin/health-check", {});
  assert(admin.admin.audit.length >= 1);
  assert(admin.profile.integrationEvents.some(event => event.action === "admin.health_check"));
  const billing = await call("/api/billing/checkout", { plan: "standard" });
  assert(billing.billingResult.status);
  assert(billing.profile.integrationEvents.some(event => event.action === "billing.checkout_requested"));
  const subscriber = await call("/api/admin/subscriber", { name: "Pilot subscriber", email: "pilot-user@example.com", plan: "pilot", seats: 1 });
  assert(subscriber.admin.subscribers.length >= 1);
  assert(subscriber.profile.integrationEvents.some(event => event.action === "subscriber.invited"));
  const testUser = await call("/api/admin/test-user", { name: "Test Family User", email: "family-test@example.com", password: "User2026!", role: "Admin", country: "Kenya", language: "sw" });
  assert(testUser.testUserResult.role === "Standard User");
  assert(testUser.admin.users.some(item => item.email === "family-test@example.com" && item.role === "Standard User"));
  assert(testUser.profile.integrationEvents.some(event => event.action === "test_user.created"));
  const adminUser = await call("/api/admin/admin-user", { name: "Admin Family User", email: "family-admin@example.com", password: "Admin2026!", role: "Standard User", country: "Nigeria", language: "en" });
  assert(adminUser.adminUserResult.role === "Admin");
  assert(adminUser.admin.users.some(item => item.email === "family-admin@example.com" && item.role === "Admin"));
  assert(adminUser.profile.integrationEvents.some(event => event.action === "admin_user.created"));
  const order = await call("/api/trade/order", { productId: "avocado-ke" });
  assert(order.profile.orders.length >= 1);
  assert(order.profile.tradeEvents.some(event => event.type === "order.created"));
  const advanced = await call("/api/trade/advance", {});
  assert(advanced.profile.orders[advanced.profile.orders.length - 1].timeline.length >= 3);
  const wallet = await call("/api/trade/wallet", { provider: "M-Pesa", amount: 120 });
  assert(wallet.profile.walletTransactions.length >= 1);
  assert(wallet.profile.integrationEvents.some(event => event.action === "wallet.transaction"));
  const buyerMessage = await call("/api/trade/message", { channel: "in-app chat", message: "Please confirm price, quality evidence, route timing, and payment terms." });
  assert(buyerMessage.tradeMessageResult.thread.status === "active");
  assert(buyerMessage.profile.tradeMessageThreads.length >= 1);
  assert(buyerMessage.profile.tradeMessages.length >= 2);
  assert(buyerMessage.profile.integrationEvents.some(event => event.action === "trade.buyer_seller_message_sent"));
  const buyerSms = await call("/api/trade/message", { channel: "SMS", message: "SMS buyer update: please confirm delivery window." });
  assert(["sent-live", "sent-local"].includes(buyerSms.tradeMessageResult.messages[0].status));
  assert(buyerSms.tradeMessageResult.delivery.status);
  assert(buyerSms.profile.integrationEvents.some(event => event.providerId === "sms-delivery" && event.action === "trade.buyer_seller_message_sent"));
  const buyerWhatsapp = await call("/api/trade/message", { channel: "WhatsApp", message: "WhatsApp buyer update: please confirm quality evidence." });
  assert(["sent-live", "sent-local"].includes(buyerWhatsapp.tradeMessageResult.messages[0].status));
  assert(buyerWhatsapp.tradeMessageResult.delivery.status);
  assert(buyerWhatsapp.profile.integrationEvents.some(event => event.providerId === "whatsapp-delivery" && event.action === "trade.buyer_seller_message_sent"));
  const buyerVideo = await call("/api/video/session", { type: "trade", videoNote: "Show crop quality, quantity, packaging, and pickup readiness to the buyer." });
  assert(buyerVideo.videoSessionResult.type === "buyer-crop-video");
  assert(buyerVideo.profile.videoSessions.length >= 1);
  assert(buyerVideo.profile.integrationEvents.some(event => event.action === "trade.buyer_video_session_ready"));
  const healthVideo = await call("/api/video/session", { type: "health", videoNote: "Show injury swelling to the telehealth provider." });
  assert(healthVideo.videoSessionResult.type === "telehealth-video");
  assert(healthVideo.profile.videoSessions.length >= 2);
  assert(healthVideo.profile.integrationEvents.some(event => event.action === "telehealth.video_session_ready"));
  const learningComms = await call("/api/communications/thread", { module: "Learning", channel: "in-app chat", message: "Please help me with this course." });
  assert(learningComms.communicationThreadResult.thread.module === "Learning");
  assert(learningComms.profile.communicationThreads.some(thread => thread.module === "Learning"));
  const workforceComms = await call("/api/communications/thread", { module: "Workforce", channel: "SMS", message: "Please confirm my next workforce step." });
  assert(workforceComms.communicationThreadResult.delivery.status);
  assert(workforceComms.profile.integrationEvents.some(event => event.action === "communication.thread_opened" && event.module === "Workforce"));
  const healthComms = await call("/api/communications/thread", { module: "Healthcare", channel: "WhatsApp", message: "Please confirm provider and caregiver support." });
  assert(healthComms.communicationThreadResult.delivery.status);
  assert(healthComms.profile.integrationEvents.some(event => event.action === "communication.thread_opened" && event.module === "Healthcare"));
  const droneMission = await call("/api/trade/drone-mission", { productId: "avocado-ke" });
  assert(droneMission.profile.droneMissions.length >= 1);
  assert(droneMission.profile.integrationEvents.some(event => event.action === "drone.flight_plan"));
  assert(droneMission.profile.mapInsights.some(item => item.type === "drone-flight-plan"));
  const drone = await call("/api/trade/drone-scan", { productId: "avocado-ke" });
  assert(drone.profile.droneScans.length >= 1);
  assert(drone.profile.droneFindings.length >= 1);
  assert(drone.profile.droneScans[0].cropHealthScore >= 55);
  assert(drone.profile.droneScans[0].farmerSummary);
  assert(drone.profile.droneFindings[0].farmerNextStep);
  assert(drone.profile.integrationEvents.some(event => event.action === "drone.field_scan"));
  assert(drone.profile.mapInsights.some(item => item.type === "drone-field-scan"));
  const droneSimple = await call("/api/agent/command", { command: "Nexus, explain the drone data in simple farmer language", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(droneSimple.commandResult.intent === "conversation.simple_data_interpretation");
  assert(droneSimple.commandResult.metadata.redirectSection === "trade");
  assert(droneSimple.commandResult.metadata.simpleCoach);
  assert(/What this means|Do this first|Watch for|Ask for help|You can say next/i.test(droneSimple.commandResult.response));
  assert(/farmer|crop|field|water|pest|route|buyer|sale/i.test(droneSimple.commandResult.response));
  const healthSimple = await call("/api/agent/command", { command: "Nexus, explain the health data in simple words", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(healthSimple.commandResult.intent === "conversation.simple_data_interpretation");
  assert(healthSimple.commandResult.metadata.redirectSection === "health");
  assert(/What this means|Do this first|danger|emergency|You can say next/i.test(healthSimple.commandResult.response));
  const learningSimple = await call("/api/agent/command", { command: "Nexus, explain the education data in simple words", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(learningSimple.commandResult.intent === "conversation.simple_data_interpretation");
  assert(learningSimple.commandResult.metadata.redirectSection === "learning");
  assert(/one lesson|low vision|hearing|You can say next|explain my lesson/i.test(learningSimple.commandResult.response));
  const workforceSimple = await call("/api/agent/command", { command: "Nexus, explain the workforce data in simple words", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(workforceSimple.commandResult.intent === "conversation.simple_data_interpretation");
  assert(workforceSimple.commandResult.metadata.redirectSection === "workforce");
  assert(/job|apply|missing skill|documents|interview|You can say next/i.test(workforceSimple.commandResult.response));
  const droneIntervention = await call("/api/trade/drone-intervention", {});
  assert(droneIntervention.profile.fieldInterventions.length >= 1);
  assert(droneIntervention.profile.integrationEvents.some(event => event.action === "drone.intervention_task"));
  assert(droneIntervention.profile.mapInsights.some(item => item.type === "drone-intervention"));
  const droneReport = await call("/api/trade/drone-advanced", { type: "field-report", productId: "avocado-ke" });
  assert(droneReport.profile.droneFieldReports.length >= 1);
  assert(droneReport.profile.integrationEvents.some(event => event.action === "drone.field_report"));
  const irrigationPlan = await call("/api/trade/drone-advanced", { type: "irrigation", productId: "avocado-ke" });
  assert(irrigationPlan.profile.droneIrrigationPlans.length >= 1);
  const pestAlert = await call("/api/trade/drone-advanced", { type: "pest", productId: "avocado-ke" });
  assert(pestAlert.profile.dronePestAlerts.length >= 1);
  const sprayPlan = await call("/api/trade/drone-advanced", { type: "spray", productId: "avocado-ke" });
  assert(sprayPlan.profile.droneSprayPlans.length >= 1);
  const yieldForecast = await call("/api/trade/drone-advanced", { type: "yield", productId: "avocado-ke" });
  assert(yieldForecast.profile.droneYieldForecasts.length >= 1);
  const droneCompliance = await call("/api/trade/drone-advanced", { type: "compliance", productId: "avocado-ke" });
  assert(droneCompliance.profile.droneComplianceAudits.length >= 1);
  assert(droneCompliance.profile.mapInsights.some(item => item.type === "drone.compliance_audit"));
  const ai = await call("/api/ai/run", { type: "command" });
  assert(ai.profile.aiActivity.length > 20);
  assert(ai.profile.aiRuns.length >= 1);
  assert(ai.profile.aiRuns[0].type === "command");
  assert(ai.profile.mapInsights.length >= 1);
  assert(ai.profile.integrationEvents.some(event => event.action === "ai.run"));
  const farmerLocation = await call("/api/map/advanced", { type: "farmer-location" });
  assert(farmerLocation.profile.farmerLocations.length >= 1);
  assert(farmerLocation.profile.integrationEvents.some(event => event.action === "map.farmer_location_mapped"));
  const fieldZone = await call("/api/map/advanced", { type: "field-zone" });
  assert(fieldZone.profile.fieldZones.length >= 1);
  assert(fieldZone.profile.integrationEvents.some(event => event.action === "map.field_zone_created"));
  const facilityRoute = await call("/api/map/advanced", { type: "facility-route" });
  assert(facilityRoute.profile.facilityRoutes.length >= 1);
  assert(facilityRoute.profile.integrationEvents.some(event => event.action === "map.facility_route_ready"));
  const routeDisruption = await call("/api/map/advanced", { type: "disruption" });
  assert(routeDisruption.profile.routeDisruptions.length >= 1);
  assert(routeDisruption.profile.integrationEvents.some(event => event.action === "map.route_disruption_recorded"));
  const riskLayer = await call("/api/map/advanced", { type: "risk-layer" });
  assert(riskLayer.profile.mapRiskLayers.length >= 1);
  assert(riskLayer.profile.integrationEvents.some(event => event.action === "map.risk_layer_generated"));
  const mapEvidence = await call("/api/map/advanced", { type: "evidence" });
  assert(mapEvidence.profile.mapEvidencePackets.length >= 1);
  assert(mapEvidence.profile.mapInsights.some(item => item.type === "map.evidence_packet_ready"));
  const tutorAi = await call("/api/ai/run", { type: "tutor" });
  assert(tutorAi.profile.aiRuns[0].type === "tutor");
  assert(tutorAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Learning"));
  const workforceAi = await call("/api/ai/run", { type: "workforce-coach" });
  assert(workforceAi.profile.aiRuns[0].type === "workforce-coach");
  assert(workforceAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Workforce"));
  const triageAi = await call("/api/ai/run", { type: "triage" });
  assert(triageAi.profile.aiRuns[0].type === "triage");
  assert(triageAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "Healthcare"));
  const tradeAi = await call("/api/ai/run", { type: "trade-advisor" });
  assert(tradeAi.profile.aiRuns[0].type === "trade-advisor");
  assert(tradeAi.profile.integrationEvents.some(event => event.action === "ai.run" && event.module === "AgriTrade"));
  const copilotAi = await call("/api/ai/run", { type: "copilot" });
  assert(copilotAi.profile.aiRuns[0].type === "copilot");
  assert(copilotAi.profile.aiRuns[0].reviewStatus === "pending-human-review");
  const orchestration = await call("/api/ai/orchestrate", { type: "copilot", note: "Smoke orchestration review" });
  assert(orchestration.aiOrchestrationResult.orchestration.topAction.title);
  assert(orchestration.profile.aiOrchestrations.length >= 1);
  assert(orchestration.profile.integrationEvents.some(event => event.action === "ai.orchestration_reviewed"));
  const reviewedAi = await call("/api/ai/review", { runId: copilotAi.profile.aiRuns[0].id, decision: "approve", note: "Smoke review" });
  assert(reviewedAi.profile.aiRuns.some(run => run.id === copilotAi.profile.aiRuns[0].id && run.reviewStatus === "approved"));
  assert(reviewedAi.profile.integrationEvents.some(event => event.action === "ai.reviewed"));
  const agentPlan = await call("/api/agent/plan", { goal: "Move a rural learner through training, workforce, telehealth, trade, maps, and AI evidence." });
  assert(agentPlan.profile.agentPlans.length >= 1);
  assert(agentPlan.profile.agentPlans[0].steps.length >= 7);
  assert(agentPlan.profile.integrationEvents.some(event => event.action === "agent.plan_created"));
  const briefing = await call("/api/agent/briefing", { purpose: "government presentation" });
  assert(briefing.profile.agentBriefings.length >= 1);
  assert(briefing.profile.integrationEvents.some(event => event.action === "agent.briefing_created"));
  const agentExecution = await call("/api/agent/execute", { planId: agentPlan.profile.agentPlans[0].id });
  assert(agentExecution.profile.agentExecutions.length >= 1);
  assert(agentExecution.profile.agentPlans[0].status === "executed");
  assert(agentExecution.profile.agentExecutions[0].status === "completed");
  assert(agentExecution.profile.agentExecutions[0].steps.every(step => step.status === "executed"));
  assert(agentExecution.profile.agentMemory.lastStatus === "completed");
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.ai.copilot"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.learning.start_or_continue"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.workforce.match_role"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.drone.flight_plan"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.drone.field_scan"));
  assert(agentExecution.profile.integrationEvents.some(event => event.action === "agent.drone.intervention_task"));
  const voiceStatus = await call("/api/agent/command", { command: "what is the readiness status", confirm: true });
  assert(voiceStatus.commandResult.intent === "readiness-summary");
  assert(voiceStatus.profile.agentCommands.length >= 1);
  assert(voiceStatus.profile.integrationEvents.some(event => event.action === "agent.command"));
  const voiceTranscript = await call("/api/voice/transcribe", { transcript: "run telehealth intake", language: "en" });
  assert(voiceTranscript.voiceResult.transcript === "run telehealth intake");
  assert(voiceTranscript.profile.voiceSessions.some(item => item.type === "speech-to-text"));
  const voiceSpeak = await call("/api/voice/speak", { text: "Telehealth command ready", language: "en" });
  assert(voiceSpeak.voiceResult.text === "Telehealth command ready");
  assert(voiceSpeak.profile.voiceSessions.some(item => item.type === "text-to-speech"));
  const phoneIncoming = await fetch(`${base}/api/voice/phone/incoming`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ From: "+15555550123", CallSid: "CA-smoke" })
  });
  const phoneIncomingXml = await phoneIncoming.text();
  assert(phoneIncoming.ok);
  assert(phoneIncomingXml.includes("<Gather"));
  const phoneGather = await fetch(`${base}/api/voice/phone/gather`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ SpeechResult: "start telehealth intake", CallSid: "CA-smoke" })
  });
  const phoneGatherXml = await phoneGather.text();
  assert(phoneGather.ok);
  assert(phoneGatherXml.includes("You can say another command"));
  const translated = await call("/api/translate", { text: "Generate care plan", targetLanguage: "sw", context: "smoke" });
  assert(translated.translationResult.targetLanguage === "sw");
  assert(translated.profile.integrationEvents.some(event => event.action === "translation.dynamic"));
  const voiceTranslated = await call("/api/translate", { text: "Telehealth intake opened for voice user", targetLanguage: "sw", context: "voice-response" });
  assert(voiceTranslated.translationResult.translatedText.includes("afya"));
  const voiceDrone = await call("/api/agent/command", { command: "run drone scan", confirm: true });
  assert(voiceDrone.commandResult.intent === "drone.field_scan");
  assert(voiceDrone.profile.droneScans.length >= 1);
  assert(voiceDrone.profile.agentCommands[0].intent === "drone.field_scan");
  const happened = await call("/api/agent/command", { command: "Nexus, what just happened?", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(happened.commandResult.response);
  const morning = await call("/api/agent/command", { command: "Good morning AgriNexus", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(morning.commandResult.response);
  const buyerContact = await call("/api/agent/command", { command: "Hey AgriTrade, I want to speak to the buyer that I am selling my crop to", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(buyerContact.commandResult.intent === "trade.buyer_contact");
  assert(buyerContact.commandResult.metadata.redirectSection === "trade");
  assert(buyerContact.commandResult.metadata.highestFunctionalityMode === true);
  assert(buyerContact.commandResult.metadata.autonomousBrain.phase === "observe-diagnose-decide-act-verify-learn");
  assert(buyerContact.profile.autonomousOperatingLoops.length >= 1);
  assert(buyerContact.profile.buyerContacts.length >= 1);
  assert(buyerContact.profile.integrationEvents.some(event => event.action === "buyer.contact_prepared"));
  const routeTracking = await call("/api/agent/command", { command: "Hey AgriTrade, track my route in real time", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(routeTracking.commandResult.intent === "map.live_route_tracking");
  assert(routeTracking.commandResult.metadata.redirectSection === "map");
  assert(routeTracking.commandResult.metadata.requiresBrowserGeolocation);
  assert(routeTracking.profile.integrationEvents.some(event => event.action === "map.live_route_tracking_requested"));
  const efficiency = await call("/api/agent/command", { command: "Hey AgriTrade, how can we improve operational efficiency for this crop route?", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(efficiency.commandResult.intent === "trade.operational_efficiency");
  assert(efficiency.commandResult.metadata.redirectSection === "trade");
  assert(efficiency.commandResult.metadata.score > 0);
  assert(efficiency.profile.tradeEfficiencyReviews.length >= 1);
  assert(efficiency.profile.integrationEvents.some(event => event.action === "trade.operational_efficiency_reviewed"));
  const tradeBrief = await call("/api/agent/command", { command: "Hey AgriTrade, prepare a buyer update for the route and payment status", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(tradeBrief.commandResult.intent === "trade.operational_communication");
  assert(tradeBrief.commandResult.metadata.redirectSection === "trade");
  assert(tradeBrief.profile.tradeCommunicationBriefs.length >= 1);
  assert(tradeBrief.profile.integrationEvents.some(event => event.action === "trade.operational_communication_prepared"));
  const buyerChat = await call("/api/agent/command", { command: "Nexus, message the buyer about this crop", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(buyerChat.commandResult.intent === "trade.buyer_seller_message");
  assert(buyerChat.commandResult.metadata.redirectSection === "trade");
  assert(buyerChat.profile.tradeMessageThreads.length >= 1);
  const stagedCropVideo = await call("/api/agent/command", { command: "Nexus, open video so I can show the buyer my crops", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(stagedCropVideo.commandResult.intent === "conversation.pending_action");
  assert(stagedCropVideo.profile.agentPendingAction.tool === "trade.buyer_video");
  const cropVideoConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(["conversation.confirmed", "trade.buyer_video"].includes(cropVideoConfirm.commandResult.intent));
  assert(cropVideoConfirm.profile.videoSessions.some(item => item.type === "buyer-crop-video"));
  const stagedInjuryVideo = await call("/api/agent/command", { command: "Nexus, video provider for patient injury", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(["conversation.pending_action", "health.video_session_ready"].includes(stagedInjuryVideo.commandResult.intent));
  if (stagedInjuryVideo.commandResult.intent === "conversation.pending_action") {
    assert(stagedInjuryVideo.profile.agentPendingAction.tool === "health.video_session");
    const injuryVideoConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
    assert(["conversation.confirmed", "health.video_session"].includes(injuryVideoConfirm.commandResult.intent));
    assert(injuryVideoConfirm.profile.videoSessions.some(item => item.type === "telehealth-video"));
  } else {
    assert(stagedInjuryVideo.profile.videoSessions.some(item => item.type === "telehealth-video"));
  }
  const contextualRoute = await call("/api/agent/command", { command: "Now check the route", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(["conversation.pending_action", "map.route_risk", "ai-question", "trade.operational_efficiency", "trade.operational_communication"].includes(contextualRoute.commandResult.intent));
  assert(contextualRoute.commandResult.metadata.redirectSection === "map" || contextualRoute.commandResult.metadata.redirectSection === "trade" || contextualRoute.commandResult.metadata.tool === "map.route_risk" || contextualRoute.commandResult.intent === "ai-question");
  const moduleHelp = await call("/api/agent/command", { command: "What can I say in telehealth?", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(moduleHelp.commandResult.intent === "voice.module_help");
  assert(moduleHelp.commandResult.metadata.redirectSection === "health");
  const guidedQuestions = await call("/api/agent/command", { command: "Nexus, ask me questions about health", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(guidedQuestions.commandResult.intent === "conversation.clarification_started");
  assert(guidedQuestions.commandResult.metadata.guidedQuestion.questionType === "care-safety-first");
  assert(guidedQuestions.commandResult.response.includes("own words"));
  const guidedUnsure = await call("/api/agent/command", { command: "I don't know", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(guidedUnsure.commandResult.intent === "conversation.clarification_followup");
  assert(guidedUnsure.commandResult.response.includes("exact words"));
  const guidedAnswer = await call("/api/agent/command", { command: "my chest hurts and I need help", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(guidedAnswer.commandResult.intent === "conversation.clarification_resolved");
  assert(guidedAnswer.commandResult.metadata.clarification.selectedTool === "health.safety");
  assert(guidedAnswer.commandResult.metadata.clarification.nextQuestion);
  if (guidedAnswer.profile.agentPendingAction) await call("/api/agent/command", { command: "no", conversational: true, inputMode: "voice", outputMode: "voice" });
  const guidedWork = await call("/api/agent/command", { command: "Nexus, ask me questions about work", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(guidedWork.commandResult.intent === "conversation.clarification_started");
  const guidedWorkAnswer = await call("/api/agent/command", { command: "I need money and a position", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(guidedWorkAnswer.commandResult.intent === "conversation.clarification_resolved");
  assert(guidedWorkAnswer.commandResult.metadata.clarification.selectedTool === "workforce.apply_role");
  if (guidedWorkAnswer.profile.agentPendingAction) await call("/api/agent/command", { command: "no", conversational: true, inputMode: "voice", outputMode: "voice" });
  const farmerGuide = await call("/api/agent/command", { command: "Nexus, guide the farmer", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(farmerGuide.commandResult.intent === "conversation.role_guidance");
  assert(farmerGuide.commandResult.metadata.roleGuide.persona === "farmer");
  assert(farmerGuide.commandResult.metadata.roleGuide.path.includes("run drone or field scan"));
  const patientGuide = await call("/api/agent/command", { command: "Nexus, support the patient", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(patientGuide.commandResult.intent === "conversation.role_guidance");
  assert(patientGuide.commandResult.metadata.roleGuide.persona === "patient");
  assert(patientGuide.commandResult.response.includes("safe intake"));
  const workerGuide = await call("/api/agent/command", { command: "Nexus, coach the worker", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(workerGuide.commandResult.intent === "conversation.role_guidance");
  assert(workerGuide.commandResult.metadata.roleGuide.persona === "worker");
  const studentGuide = await call("/api/agent/command", { command: "Nexus, guide the student", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(studentGuide.commandResult.intent === "conversation.role_guidance");
  assert(studentGuide.commandResult.metadata.roleGuide.persona === "student");
  const learnerGuide = await call("/api/agent/command", { command: "Nexus, guide the learner", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(learnerGuide.commandResult.intent === "conversation.role_guidance");
  assert(learnerGuide.commandResult.metadata.roleGuide.persona === "learner");
  const voiceMission = await call("/api/agent/command", { command: "help this farmer sell maize safely from start to finish", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(["conversation.pending_action", "conversation.clarification_started"].includes(voiceMission.commandResult.intent));
  if (voiceMission.commandResult.intent === "conversation.pending_action") {
    assert(voiceMission.commandResult.metadata.mode === "autopilot");
    assert(voiceMission.commandResult.metadata.previewSteps.length >= 6);
  } else {
    assert(voiceMission.profile.agentMemory.activeClarification);
    assert(voiceMission.commandResult.metadata.suggestedReplies.includes("contact buyer"));
    const clarifiedVoiceMission = await call("/api/agent/command", { command: "contact buyer", conversational: true, inputMode: "voice", outputMode: "voice" });
    assert(["conversation.clarification_resolved", "trade.buyer_contact", "trade.buyer_seller_message"].includes(clarifiedVoiceMission.commandResult.intent));
    assert(clarifiedVoiceMission.profile.agentPendingAction || clarifiedVoiceMission.profile.buyerContacts.length >= 1 || clarifiedVoiceMission.profile.tradeMessageThreads.length >= 1);
  }
  if (voiceMission.profile.agentPendingAction) {
    const voiceMissionCancel = await call("/api/agent/command", { command: "no", conversational: true, inputMode: "voice", outputMode: "voice" });
    assert(voiceMissionCancel.commandResult.intent === "conversation.canceled");
  }
  const localizedBuyer = await call("/api/agent/command", { command: "contacter acheteur", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(["conversation.pending_action", "trade.buyer_contact", "trade.buyer_seller_message", "trade.operational_communication"].includes(localizedBuyer.commandResult.intent));
  if (localizedBuyer.profile.agentPendingAction) await call("/api/agent/command", { command: "no", conversational: true, inputMode: "voice", outputMode: "voice" });
  const recovery = await call("/api/agent/command", { command: "qzxv blorf", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(recovery.commandResult.response);
  const voiceDemo = await call("/api/agent/command", { command: "run investor voice demo", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(voiceDemo.commandResult.intent === "agent.voice_demo_mode");
  assert(voiceDemo.profile.integrationEvents.some(event => event.action === "agent.voice_demo_completed"));
  const outbreakCheck = await call("/api/agent/command", { command: "Telehealth, is the Congo region infected with Ebola right now?", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(outbreakCheck.commandResult.intent === "health.public_health_risk");
  assert(outbreakCheck.commandResult.metadata.redirectSection === "health");
  assert(outbreakCheck.commandResult.response.toLowerCase().includes("ebola"));
  assert(outbreakCheck.profile.publicHealthChecks.length >= 1);
  assert(outbreakCheck.profile.integrationEvents.some(event => event.action === "health.public_health_risk_checked"));
  const quote = await call("/api/trade/advanced", { type: "quote", productId: "avocado-ke" });
  assert(quote.profile.tradeQuotes.length >= 1);
  assert(quote.profile.integrationEvents.some(event => event.action === "quote.sent"));
  const quality = await call("/api/trade/advanced", { type: "quality", productId: "avocado-ke" });
  assert(quality.profile.qualityInspections.length >= 1);
  const coldChain = await call("/api/trade/advanced", { type: "cold-chain", productId: "avocado-ke" });
  assert(coldChain.profile.coldChainChecks.length >= 1);
  const exportPacket = await call("/api/trade/advanced", { type: "export", productId: "avocado-ke" });
  assert(exportPacket.profile.exportReadiness.length >= 1);
  const contract = await call("/api/trade/advanced", { type: "contract", productId: "avocado-ke" });
  assert(contract.profile.contractPackets.length >= 1);
  const release = await call("/api/trade/advanced", { type: "release", productId: "avocado-ke" });
  assert(release.profile.paymentReleases.length >= 1);
  const workforceApply = await call("/api/agent/command", { command: "Workforce, I want to apply for that job can you help me", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(["workforce.application_submitted", "workforce.application_help"].includes(workforceApply.commandResult.intent));
  assert(workforceApply.commandResult.metadata.redirectSection === "workforce");
  const conversationalApply = await call("/api/agent/command", { command: "I want to apply for that job", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(conversationalApply.commandResult.intent === "conversation.pending_action");
  assert(conversationalApply.commandResult.status === "needs-confirmation");
  assert(conversationalApply.profile.agentPendingAction.kind === "workforce-application");
  assert(conversationalApply.profile.agentConversation.length >= 2);
  const conversationalConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(conversationalConfirm.commandResult.intent === "conversation.confirmed");
  assert(!conversationalConfirm.profile.agentPendingAction);
  assert(conversationalConfirm.commandResult.metadata.redirectSection === "workforce");
  const guidedHealth = await call("/api/agent/command", { command: "health", conversational: true });
  assert(guidedHealth.commandResult.intent === "conversation.pending_action");
  assert(guidedHealth.commandResult.metadata.redirectSection === "health");
  const cancelGuidedHealth = await call("/api/agent/command", { command: "no", conversational: true });
  assert(cancelGuidedHealth.commandResult.intent === "conversation.canceled");
  const telehealthGuide = await call("/api/agent/command", { command: "walk me through telehealth", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(telehealthGuide.commandResult.intent === "conversation.platform_guide");
  assert(telehealthGuide.commandResult.status === "guiding");
  assert(telehealthGuide.commandResult.metadata.redirectSection === "health");
  assert(telehealthGuide.commandResult.metadata.suggestedCommand);
  assert(!telehealthGuide.profile.agentPendingAction);
  const learningGuide = await call("/api/agent/command", { command: "I am new, how do I start training", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(learningGuide.commandResult.intent === "conversation.platform_guide");
  assert(learningGuide.commandResult.metadata.redirectSection === "learning");
  const memoryHelp = await call("/api/agent/command", { command: "help me", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(memoryHelp.commandResult.intent === "conversation.guided_menu");
  assert(memoryHelp.commandResult.metadata.recommendedAction);
  assert(memoryHelp.commandResult.metadata.redirectSection);
  const tenItemModel = await call("/api/agent/command", { command: "show me all 10 items", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(tenItemModel.commandResult.intent === "intelligent-assistant.ten_item_model");
  assert(tenItemModel.commandResult.metadata.model.total === 10);
  assert(tenItemModel.commandResult.metadata.redirectSection === "agent");
  const allEight = await call("/api/agent/command", { command: "Nexus, show all 8 reasoning and language production upgrades", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(allEight.commandResult.intent === "conversation.reasoning_language_production");
  assert(allEight.commandResult.metadata.reasoningLanguageProduction.total === 8);
  assert(allEight.commandResult.metadata.reasoningLanguageProduction.layers.some(item => item.id === "reasoning-before-action"));
  assert(allEight.profile.agentMemory.lastReasoningLanguageProduction.total === 8);
  const directAllEight = await call("/api/agent/reasoning-language", { command: "Review all eight for a farmer speaking French", targetLanguage: "fr" });
  assert(directAllEight.reasoningLanguageProduction.total === 8);
  assert(directAllEight.reasoningLanguageProduction.targetLanguage === "fr");
  const deepOperating = await call("/api/agent/command", { command: "Nexus, go deeper on live engine awareness", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(deepOperating.commandResult.intent === "conversation.deep_operating_intelligence");
  assert(deepOperating.commandResult.metadata.deepOperatingIntelligence.moduleDepth.length >= 6);
  assert(deepOperating.commandResult.metadata.deepOperatingIntelligence.deferred.some(item => item.id === "billing-subscriptions"));
  assert(deepOperating.profile.agentMemory.lastDeepOperatingIntelligence.status);
  const deepEndpoint = await call("/api/intelligence/deep-operating");
  assert(deepEndpoint.moduleDepth.length >= 6);
  assert(deepEndpoint.autonomy.actsWithConfirmation === true);
  const noVendorTen = await call("/api/agent/command", { command: "Nexus, do all 10 without adding real credentials", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(noVendorTen.commandResult.intent === "conversation.no_vendor_upgrade_ten");
  assert(noVendorTen.commandResult.metadata.noVendorUpgradeTen.total === 10);
  assert(noVendorTen.profile.noVendorUpgradeRuns.length >= 1);
  assert(noVendorTen.profile.localScenarioMissions.length >= 4);
  const noVendorEndpoint = await call("/api/intelligence/no-vendor-ten", { persist: true });
  assert(noVendorEndpoint.noVendorUpgradeTenResult.readyCount === 10);
  assert(noVendorEndpoint.noVendorUpgradeTenResult.missionBlueprints.length === 4);
  const maxEfficiency = await call("/api/agent/command", { command: "Nexus, maximum operational efficiency", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(maxEfficiency.commandResult.intent === "conversation.maximum_operational_efficiency");
  assert(maxEfficiency.commandResult.metadata.maximumOperationalEfficiency.overallScore > 0);
  assert(maxEfficiency.commandResult.metadata.maximumOperationalEfficiency.recommendedSequence.length >= 3);
  assert(maxEfficiency.profile.operationalEfficiencyRuns.length >= 1);
  const maxEfficiencyEndpoint = await call("/api/intelligence/maximum-efficiency", { persist: true });
  assert(maxEfficiencyEndpoint.maximumOperationalEfficiencyResult.moduleScores.length >= 6);
  assert(maxEfficiencyEndpoint.maximumOperationalEfficiencyResult.automationOpportunities.length >= 5);
  const autonomousLoop = await call("/api/agent/command", { command: "Nexus, run autonomous operating loop", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(autonomousLoop.commandResult.intent === "conversation.autonomous_operating_loop");
  assert(autonomousLoop.commandResult.metadata.autonomousOperatingLoop.phases.length === 6);
  assert(autonomousLoop.commandResult.metadata.autonomousOperatingLoop.phases.some(item => item.id === "verify"));
  assert(autonomousLoop.profile.autonomousOperatingLoops.length >= 1);
  const autonomousLoopEndpoint = await call("/api/intelligence/autonomous-loop", { persist: true });
  assert(autonomousLoopEndpoint.autonomousOperatingLoopResult.currentDecision.command);
  assert(autonomousLoopEndpoint.autonomousOperatingLoopResult.evidenceChecklist.length >= 5);
  const progressSummaryCommand = await call("/api/agent/command", { command: "summarize my progress", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(progressSummaryCommand.commandResult.intent === "conversation.progress_summary");
  assert(progressSummaryCommand.commandResult.metadata.redirectSection === "dashboard");
  assert(progressSummaryCommand.commandResult.response.includes("Here is your progress"));
  const investorTourCommand = await call("/api/agent/command", { command: "present the platform", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(investorTourCommand.commandResult.intent === "conversation.investor_presentation_mode");
  assert(investorTourCommand.commandResult.metadata.redirectSection === "dashboard");
  assert(investorTourCommand.profile.agentBriefings.length >= 1);
  const behaviorCommand = await call("/api/agent/command", { command: "explain your behavior model", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(behaviorCommand.commandResult.intent === "conversation.behavior_model");
  assert(behaviorCommand.commandResult.metadata.behaviorModel.id === "human-guide-behavior-model");
  assert(behaviorCommand.commandResult.metadata.behaviorModel.interactionStyle.includes("one-step"));
  assert(behaviorCommand.commandResult.metadata.behaviorModel.followUp);
  assert(behaviorCommand.commandResult.response.includes("Would you like") || behaviorCommand.commandResult.response.includes("guide"));
  const intakeStart = await call("/api/agent/command", { command: "start telehealth intake and ask me questions", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakeStart.commandResult.intent === "conversation.intake_started");
  assert(intakeStart.profile.agentMemory.activeIntake.domain === "health");
  const intakePatient = await call("/api/agent/command", { command: "Amina Diallo", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakePatient.commandResult.intent === "conversation.intake_question");
  const intakeNeed = await call("/api/agent/command", { command: "She needs heat exposure review and accessible care", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakeNeed.commandResult.intent === "conversation.intake_question");
  const intakeLanguage = await call("/api/agent/command", { command: "French", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakeLanguage.commandResult.intent === "conversation.intake_question");
  const intakeAccess = await call("/api/agent/command", { command: "Captions and caregiver handoff", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakeAccess.commandResult.intent === "conversation.intake_question");
  const intakeReady = await call("/api/agent/command", { command: "Voice callback plus SMS", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakeReady.commandResult.intent === "conversation.intake_ready");
  assert(intakeReady.profile.agentPendingAction.kind === "conversational-intake");
  assert(intakeReady.profile.agentMemory.conversationalIntakes.length >= 1);
  const intakeApply = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(intakeApply.commandResult.intent === "conversation.confirmed");
  assert(intakeApply.commandResult.metadata.redirectSection === "health");
  assert(intakeApply.profile.healthIntakes.some(item => item.patientName === "Amina Diallo"));
  assert(intakeApply.profile.agentMemory.preferences.some(item => item.text.includes("Amina Diallo")));
  const agenticOpenCommand = await call("/api/agent/command", { command: "My field has crop stress and I need evidence before selling", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agenticOpenCommand.commandResult.intent === "conversation.pending_action");
  assert(["drone.field_scan", "trade.market_review", "drone.intervention_task"].includes(agenticOpenCommand.commandResult.metadata.tool));
  assert(agenticOpenCommand.profile.agentPendingAction.tool);
  const agenticConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agenticConfirm.commandResult.intent === "conversation.confirmed");
  assert(!agenticConfirm.profile.agentPendingAction);
  const agritradeGreeting = await call("/api/agent/command", { command: "Hi AgriTrade, my name is Ron", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeGreeting.commandResult.intent === "trade.conversational_greeting");
  assert(agritradeGreeting.commandResult.response.includes("Hello Ron"));
  assert(agritradeGreeting.commandResult.metadata.redirectSection === "trade");
  assert(agritradeGreeting.profile.agentMemory.userName === "Ron");
  const agritradeIntro = await call("/api/agent/command", { command: "Hey AgriTrade tell me about the platform and what you do", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeIntro.commandResult.intent === "trade.module_introduction");
  assert(agritradeIntro.commandResult.response.includes("AgriTrade helps farmers"));
  assert(agritradeIntro.commandResult.metadata.redirectSection === "trade");
  const agritradeSpanish = await call("/api/agent/command", { command: "Hey AgriTrade can you change the language from English to Spanish", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeSpanish.commandResult.intent === "conversation.language_changed");
  assert(agritradeSpanish.commandResult.metadata.language === "es");
  assert(agritradeSpanish.user.language === "es");
  assert(agritradeSpanish.profile.accessibilityProfile.language === "es");
  const agritradeFrench = await call("/api/agent/command", { command: "Hey AgriTrade, speak French", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeFrench.commandResult.intent === "conversation.language_changed");
  assert(agritradeFrench.commandResult.metadata.language === "fr");
  const agritradeLocalizedEnglish = await call("/api/agent/command", { command: "Hey AgriTrade, parle anglais", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeLocalizedEnglish.commandResult.intent === "conversation.language_changed");
  assert(agritradeLocalizedEnglish.commandResult.metadata.language === "en");
  const agritradeSwahili = await call("/api/agent/command", { command: "Hey AgriTrade, switch to Kenya", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeSwahili.commandResult.intent === "conversation.language_changed");
  assert(agritradeSwahili.commandResult.metadata.language === "sw");
  const agritradeArabic = await call("/api/agent/command", { command: "Hey AgriTrade, use Arabic", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeArabic.commandResult.intent === "conversation.language_changed");
  assert(agritradeArabic.commandResult.metadata.language === "ar");
  const agritradeEnglish = await call("/api/agent/command", { command: "Hey AgriTrade, switch to Nigeria", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(agritradeEnglish.commandResult.intent === "conversation.language_changed");
  assert(agritradeEnglish.commandResult.metadata.language === "en");
  assert(agritradeEnglish.user.language === "en");
  const rememberPreference = await call("/api/agent/command", { command: "Remember that I prefer voice-first telehealth support for hearing impaired patients", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(rememberPreference.commandResult.intent === "memory-updated");
  assert(rememberPreference.profile.agentMemory.preferences.length >= 1);
  const memoryRouted = await call("/api/agent/command", { command: "A patient cannot hear and needs care access", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(memoryRouted.commandResult.intent === "conversation.pending_action");
  assert(memoryRouted.commandResult.metadata.memoriesUsed.length >= 1);
  assert(memoryRouted.profile.integrationEvents.some(event => event.action === "agent.memory_retrieved"));
  const memorySummary = await call("/api/agent/command", { command: "what have you learned", conversational: true });
  assert(memorySummary.commandResult.intent === "memory-summary");
  assert(memorySummary.commandResult.response.includes("voice-first telehealth"));
  const dailyWalkAdvisor = await call("/api/agent/command", { command: "Nexus, grandma wants to walk today but it is 90 degrees. Is it too hot?", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(dailyWalkAdvisor.commandResult.intent === "conversation.daily_life_advisor");
  assert(dailyWalkAdvisor.commandResult.metadata.kind === "walking-heat");
  assert(dailyWalkAdvisor.commandResult.metadata.reasoning);
  assert(dailyWalkAdvisor.commandResult.response.includes("90 degrees"));
  const farmerCuriousAdvisor = await call("/api/agent/command", { command: "Nexus, a farmer is curious when to harvest but does not have all the data", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(farmerCuriousAdvisor.commandResult.intent === "conversation.daily_life_advisor");
  assert(farmerCuriousAdvisor.commandResult.metadata.kind === "farmer");
  const autopilotPreview = await call("/api/agent/command", { command: "Nexus autopilot help this farmer get from crop problem to buyer payment", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(["conversation.pending_action", "agent.agrinexus_mode_staged"].includes(autopilotPreview.commandResult.intent));
  assert(autopilotPreview.commandResult.metadata.mode === "autopilot");
  assert(autopilotPreview.commandResult.metadata.previewSteps.length >= 6);
  const autopilotConfirm = await call("/api/agent/command", { command: "yes", conversational: true, inputMode: "voice", outputMode: "voice" });
  assert(autopilotConfirm.commandResult.intent === "conversation.confirmed");
  assert(autopilotConfirm.commandResult.metadata.mode === "autopilot");
  assert(autopilotConfirm.profile.agentExecutions[0].status === "completed");
  assert(autopilotConfirm.profile.integrationEvents.some(event => event.action === "agent.autopilot_executed"));
  const lessonCommand = await call("/api/agent/command", { command: "Nexus complete my lesson", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(lessonCommand.commandResult.intent === "learning.complete_lesson");
  assert(lessonCommand.commandResult.metadata.redirectSection === "learning");
  const certificateCommand = await call("/api/agent/command", { command: "Nexus issue my certificate", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(certificateCommand.commandResult.intent === "learning.certificate");
  assert(certificateCommand.profile.certificates.length >= 1);
  const vitalsCommand = await call("/api/agent/command", { command: "Nexus capture vitals for telehealth", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(vitalsCommand.commandResult.intent === "health.vitals");
  assert(vitalsCommand.commandResult.metadata.redirectSection === "health");
  const shiftCommand = await call("/api/agent/command", { command: "Nexus schedule my shift", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(shiftCommand.commandResult.intent === "workforce.schedule_shift");
  assert(shiftCommand.profile.shiftSchedule.length >= 1);
  const engineCommand = await call("/api/agent/command", { command: "Nexus test provider engines", confirm: true, inputMode: "voice", outputMode: "voice" });
  assert(engineCommand.commandResult.intent === "integrations.test_all");
  assert(engineCommand.commandResult.metadata.redirectSection === "integrations");
  const govtBriefing = await call("/api/agent/command", { command: "Nexus, prepare a government briefing", confirm: true });
  assert(govtBriefing.commandResult.intent === "government-briefing");
  assert(govtBriefing.profile.agentBriefings.length >= 1);
  const farmerPlan = await call("/api/agent/command", { command: "Nexus, onboard a farmer in Kenya", confirm: false });
  assert(farmerPlan.commandResult.intent === "create-agent-plan");
  assert(farmerPlan.profile.agentMemory.lastStatus === "awaiting-approval");
  const jarvisMission = await call("/api/agent/command", { command: "Nexus, run full mission", confirm: true });
  assert(jarvisMission.commandResult.intent === "full-agent-mission");
  assert(jarvisMission.profile.agentExecutions[0].status === "completed");
  const notice = await call("/api/notifications/send", { module: "Learning", channel: "workflow", message: "Learning notification smoke" });
  assert(notice.profile.notifications.some(item => item.module === "Learning"));
  assert(notice.profile.integrationEvents.some(event => event.action === "notification.sent" && event.module === "Learning"));
  const demo = await call("/api/demo/run", {});
  assert(demo.profile.activity.some(item => item.includes("Executive demo run completed")));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.learning_completed"));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.workforce_synced"));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.health_case_opened"));
  assert(demo.profile.integrationEvents.some(event => event.action === "demo.trade_order_created"));
  assert(demo.profile.notifications.some(item => item.channel === "executive-demo"));
  const wowDemo = await call("/api/demo/wow", {});
  assert(wowDemo.profile.demoScore === 100);
  assert(wowDemo.profile.demoMoments.length >= 6);
  assert(wowDemo.profile.learningAccommodations.length >= 3);
  assert(wowDemo.profile.telehealthAccessibility.length >= 3);
  assert(wowDemo.profile.integrationEvents.some(event => event.action === "wow.telehealth_accessible"));
  assert(wowDemo.profile.integrationEvents.some(event => event.action === "wow.ai_orchestration"));
  assert(wowDemo.profile.notifications.some(item => item.channel === "wow-demo"));
  const liveInvestor = await call("/api/demo/investor-live", { scenario: "farmer-market" });
  assert(liveInvestor.liveInvestorDemoResult.demo.status === "complete");
  assert(liveInvestor.profile.liveInvestorDemos.length >= 1);
  assert(liveInvestor.impactDashboard.metrics.length >= 7);
  assert(liveInvestor.missionTimeline.stages.length >= 6);
  assert(liveInvestor.profile.integrationEvents.some(event => event.action === "demo.investor_live_completed"));
  const evidencePacket = await call("/api/evidence/export", { audience: "investor" });
  assert(evidencePacket.evidenceExportResult.content.includes("AgriNexus Evidence Packet"));
  assert(evidencePacket.profile.evidenceExports.length >= 1);
  server.kill();
  fs.rmSync(tempDbPath, { force: true });
  console.log("Smoke test passed");
})().catch(error => {
  if (serverProcess && !serverProcess.killed) serverProcess.kill();
  fs.rmSync(tempDbPath, { force: true });
  console.error(error.message);
  process.exit(1);
});
